/**
 * @file src/csharp_emitter/cs_file_emitter.cpp
 * @brief Top-level C# source file generator.
 */

#include "retdec/csharp_emitter/cs_file_emitter.h"

#include <algorithm>
#include <cassert>
#include <sstream>

namespace retdec {
namespace csharp_emitter {

// ─── CsFileEmitter ───────────────────────────────────────────────────────────

CsFileEmitter::CsFileEmitter(CsEmitOptions opts) : opts_(std::move(opts)) {}

// ─── Helpers ─────────────────────────────────────────────────────────────────

CsWriter::Options CsFileEmitter::makeWriterOptions() const {
    CsWriter::Options wo;
    wo.csharpVersion = opts_.csharpVersion;
    wo.emitXmlDoc    = opts_.emitXmlDoc;
    return wo;
}

std::string CsFileEmitter::namespaceOf(const BcClass& cls) const {
    return cls.packageName.empty() ? "" : cls.packageName;
}

std::string CsFileEmitter::makeFileName(const BcClass& cls) const {
    std::string ns = namespaceOf(cls);
    std::string name = cls.name;
    // Replace < > with empty for generic names
    name.erase(std::remove_if(name.begin(), name.end(), [](char c){
        return c == '<' || c == '>';
    }), name.end());

    if (ns.empty()) return name + ".cs";
    // Convert namespace separator (. or /) to /
    std::string dir = ns;
    for (char& c : dir) if (c == '.') c = '/';
    return dir + "/" + name + ".cs";
}

bool CsFileEmitter::shouldSkip(const BcClass& cls) const {
    if (!opts_.omitCompilerGenerated) return false;
    // Skip state machines and other compiler artefacts
    if (cls.name.find('<') != std::string::npos) return true;
    for (const auto& ann : cls.annotations) {
        if (ann.typeName.find("CompilerGenerated") != std::string::npos) return true;
    }
    return false;
}

// ─── Header / directives ─────────────────────────────────────────────────────

std::string CsFileEmitter::makeHeader(const BcModule& module) const {
    if (!opts_.emitAutoGenHeader) return "";
    std::ostringstream ss;
    ss << "// <auto-generated by retdec decompiler>\n";
    if (opts_.emitAssemblyInfo)
        ss << "// Assembly: " << module.name() << "\n";
    ss << "\n";
    return ss.str();
}

std::string CsFileEmitter::makeNullableDirective() const {
    if (!opts_.nullableEnable) return "";
    return "#nullable enable\n\n";
}

void CsFileEmitter::emitNamespaceHeader(CsWriter& w, const std::string& ns) const {
    if (ns.empty()) return;
    if (opts_.fileScopedNamespace && opts_.csharpVersion >= 10) {
        w.line("namespace " + ns + ";");
        w.blank();
    } else {
        w.line("namespace " + ns);
        w.openBrace();
    }
}

void CsFileEmitter::emitNamespaceFooter(CsWriter& w, const std::string& ns) const {
    if (ns.empty()) return;
    if (!(opts_.fileScopedNamespace && opts_.csharpVersion >= 10)) {
        w.closeBrace();
    }
}

// ─── Using directives ─────────────────────────────────────────────────────────

void CsFileEmitter::collectNamespaces(
        const BcClass& cls,
        const std::unordered_map<std::string, CilReconstructResult>&,
        std::vector<std::string>& namespaces) const {
    // Scan all types referenced by the class (fields, methods, bases)
    auto addNs = [&](const std::string& fqn) {
        size_t lastDot = fqn.rfind('.');
        if (lastDot != std::string::npos) {
            std::string ns = fqn.substr(0, lastDot);
            if (ns != cls.packageName)
                namespaces.push_back(ns);
        }
    };

    if (cls.superClass.has_value())
        addNs(cls.superClass->toString());
    for (const auto& iface : cls.interfaces)
        addNs(iface.toString());
    for (const auto& f : cls.fields)
        addNs(f.type.toString());
    for (const auto& m : cls.methods) {
        if (m.descriptor.returnType)
            addNs(m.descriptor.returnType->toString());
        for (const auto& p : m.descriptor.params)
            addNs(p->toString());
    }
}

std::vector<std::string> CsFileEmitter::computeUsings(
        const BcClass& cls,
        const BcModule& module,
        const std::unordered_map<std::string, CilReconstructResult>& results) const {
    std::vector<std::string> namespaces;
    // Always include common namespaces
    namespaces.push_back("System");
    namespaces.push_back("System.Collections.Generic");

    collectNamespaces(cls, results, namespaces);

    // De-duplicate
    std::sort(namespaces.begin(), namespaces.end());
    namespaces.erase(std::unique(namespaces.begin(), namespaces.end()), namespaces.end());

    // Remove own namespace
    std::string ownNs = namespaceOf(cls);
    namespaces.erase(std::remove(namespaces.begin(), namespaces.end(), ownNs), namespaces.end());

    // Remove clearly invalid entries
    namespaces.erase(std::remove_if(namespaces.begin(), namespaces.end(),
        [](const std::string& ns) {
            return ns.empty() || ns.find('[') != std::string::npos ||
                   ns.find('<') != std::string::npos;
        }), namespaces.end());

    return namespaces;
}

std::string CsFileEmitter::emitUsingDirectives(
        const std::vector<std::string>& usings,
        const std::string& ownNamespace) const {
    std::ostringstream ss;
    if (!opts_.groupUsings) {
        for (const auto& ns : usings)
            ss << "using " << ns << ";\n";
        ss << "\n";
        return ss.str();
    }

    // Group: System, Microsoft, third-party
    std::vector<std::string> systemNs, microsoftNs, otherNs;
    for (const auto& ns : usings) {
        if (ns.substr(0, 7) == "System.")  systemNs.push_back(ns);
        else if (ns == "System")           systemNs.push_back(ns);
        else if (ns.substr(0, 10) == "Microsoft.") microsoftNs.push_back(ns);
        else otherNs.push_back(ns);
    }

    auto emitGroup = [&](const std::vector<std::string>& grp) {
        for (const auto& ns : grp) ss << "using " << ns << ";\n";
        if (!grp.empty()) ss << "\n";
    };

    emitGroup(systemNs);
    emitGroup(microsoftNs);
    emitGroup(otherNs);

    return ss.str();
}

// ─── hasTopLevelStatements ───────────────────────────────────────────────────

bool CsFileEmitter::hasTopLevelStatements(const BcModule& module) const {
    if (opts_.csharpVersion < 9) return false;
    for (const auto& cls : module.classes()) {
        if (cls.name == "<Module>" || cls.name == "Program") {
            for (const auto& m : cls.methods) {
                if (m.name == "Main" || m.name == "<Main>$") return true;
            }
        }
    }
    return false;
}

std::string CsFileEmitter::emitTopLevelStatements(
        const BcModule& module,
        const std::unordered_map<std::string, CilReconstructResult>& results) const {
    CsWriter w(makeWriterOptions());
    CsExprEmitter exprE(w);
    CsStmtEmitter stmtE(w, exprE);

    w.write(makeHeader(module));

    // Find Main method body
    for (const auto& cls : module.classes()) {
        if (cls.name != "<Module>" && cls.name != "Program") continue;
        for (const auto& m : cls.methods) {
            if (m.name != "Main" && m.name != "<Main>$") continue;
            auto it = results.find(m.name);
            if (it != results.end()) {
                stmtE.emitBody(it->second.method.body);
            }
        }
    }
    return w.str();
}

// ─── emitClass ────────────────────────────────────────────────────────────────

std::string CsFileEmitter::emitClass(
        const BcClass& cls,
        const BcModule& module,
        const std::unordered_map<std::string, CilReconstructResult>& results) const {
    CsWriter w(makeWriterOptions());
    CsExprEmitter exprE(w);
    CsStmtEmitter stmtE(w, exprE);

    CsTypeEmitter::Options typeOpts;
    typeOpts.omitCompilerGenerated = opts_.omitCompilerGenerated;
    typeOpts.emitXmlDoc            = opts_.emitXmlDoc;
    typeOpts.preferAutoProperties  = opts_.preferAutoProperties;
    typeOpts.csharpVersion         = opts_.csharpVersion;
    CsTypeEmitter typeE(w, exprE, stmtE, typeOpts);

    // Header + nullable
    w.write(makeHeader(module));
    w.write(makeNullableDirective());

    // Using directives
    auto usings = computeUsings(cls, module, results);
    std::string ownNs = namespaceOf(cls);
    w.write(emitUsingDirectives(usings, ownNs));

    // Namespace header
    emitNamespaceHeader(w, ownNs);

    // Type declaration
    typeE.emitClass(cls, results, module);

    // Namespace footer
    emitNamespaceFooter(w, ownNs);

    return w.str();
}

// ─── emitModule ──────────────────────────────────────────────────────────────

CsFileEmitResult CsFileEmitter::emitModule(
        const BcModule& module,
        const std::unordered_map<std::string, CilReconstructResult>& results) const {
    CsFileEmitResult result;

    // Check for top-level statements (Program.cs)
    if (hasTopLevelStatements(module)) {
        result.files["Program.cs"] = emitTopLevelStatements(module, results);
    }

    for (const auto& cls : module.classes()) {
        ++result.totalClasses;
        result.totalMethods += static_cast<int>(cls.methods.size());

        if (shouldSkip(cls)) {
            ++result.skippedClasses;
            continue;
        }

        try {
            std::string src = emitClass(cls, module, results);
            std::string fname = makeFileName(cls);
            result.files[fname] = std::move(src);
            ++result.emittedClasses;
            result.emittedMethods += static_cast<int>(cls.methods.size());
        } catch (const std::exception& e) {
            result.errors.push_back("Error emitting " + cls.fqName + ": " + e.what());
        }
    }

    return result;
}

} // namespace csharp_emitter
} // namespace retdec
