/**
 * @file src/capstone2llvmir/sysz/sysz_init.cpp
 * @brief Initializations for SystemZ implementation of @c Capstone2LlvmIrTranslator.
 * @copyright (c) 2025-2026 Odin Loch trading as Imortek
 */

#include "capstone2llvmir/sysz/sysz_impl.h"

namespace retdec {
namespace capstone2llvmir {

void Capstone2LlvmIrTranslatorSysz_impl::initializeArchSpecific()
{
	// Nothing.
}

void Capstone2LlvmIrTranslatorSysz_impl::initializeRegNameMap()
{
	// Capstone names GPRs; CC is modelled as an extra 8-bit PSW condition code.
	_reg2name = {
			{SYSZ_REG_CC, "cc"},
	};
}

void Capstone2LlvmIrTranslatorSysz_impl::initializeRegTypeMap()
{
	auto* i8 = llvm::IntegerType::getInt8Ty(_module->getContext());
	auto* i32 = llvm::IntegerType::getInt32Ty(_module->getContext());
	auto* i64 = llvm::IntegerType::getInt64Ty(_module->getContext());
	auto* i128 = llvm::IntegerType::getInt128Ty(_module->getContext());
	auto* f64 = llvm::Type::getDoubleTy(_module->getContext());
	auto* f128 = llvm::Type::getFP128Ty(_module->getContext());

	auto* f32 = llvm::Type::getFloatTy(_module->getContext());

	std::map<uint32_t, llvm::Type*> r2t = {
			{SYSZ_REG_CC, i8},

			{SYSZ_REG_F0Q, f128},
			{SYSZ_REG_F1Q, f128},
			{SYSZ_REG_F4Q, f128},
			{SYSZ_REG_F5Q, f128},
			{SYSZ_REG_F8Q, f128},
			{SYSZ_REG_F9Q, f128},
			{SYSZ_REG_F12Q, f128},
			{SYSZ_REG_F13Q, f128},

			{SYSZ_REG_A0, i32},
			{SYSZ_REG_A1, i32},
			{SYSZ_REG_A2, i32},
			{SYSZ_REG_A3, i32},
			{SYSZ_REG_A4, i32},
			{SYSZ_REG_A5, i32},
			{SYSZ_REG_A6, i32},
			{SYSZ_REG_A7, i32},
			{SYSZ_REG_A8, i32},
			{SYSZ_REG_A9, i32},
			{SYSZ_REG_A10, i32},
			{SYSZ_REG_A11, i32},
			{SYSZ_REG_A12, i32},
			{SYSZ_REG_A13, i32},
			{SYSZ_REG_A14, i32},
			{SYSZ_REG_A15, i32},

			{SYSZ_REG_C0, i32},
			{SYSZ_REG_C1, i32},
			{SYSZ_REG_C2, i32},
			{SYSZ_REG_C3, i32},
			{SYSZ_REG_C4, i32},
			{SYSZ_REG_C5, i32},
			{SYSZ_REG_C6, i32},
			{SYSZ_REG_C7, i32},
			{SYSZ_REG_C8, i32},
			{SYSZ_REG_C9, i32},
			{SYSZ_REG_C10, i32},
			{SYSZ_REG_C11, i32},
			{SYSZ_REG_C12, i32},
			{SYSZ_REG_C13, i32},
			{SYSZ_REG_C14, i32},
			{SYSZ_REG_C15, i32},

			{SYSZ_REG_V0, i128},
			{SYSZ_REG_V1, i128},
			{SYSZ_REG_V2, i128},
			{SYSZ_REG_V3, i128},
			{SYSZ_REG_V4, i128},
			{SYSZ_REG_V5, i128},
			{SYSZ_REG_V6, i128},
			{SYSZ_REG_V7, i128},
			{SYSZ_REG_V8, i128},
			{SYSZ_REG_V9, i128},
			{SYSZ_REG_V10, i128},
			{SYSZ_REG_V11, i128},
			{SYSZ_REG_V12, i128},
			{SYSZ_REG_V13, i128},
			{SYSZ_REG_V14, i128},
			{SYSZ_REG_V15, i128},
			{SYSZ_REG_V16, i128},
			{SYSZ_REG_V17, i128},
			{SYSZ_REG_V18, i128},
			{SYSZ_REG_V19, i128},
			{SYSZ_REG_V20, i128},
			{SYSZ_REG_V21, i128},
			{SYSZ_REG_V22, i128},
			{SYSZ_REG_V23, i128},
			{SYSZ_REG_V24, i128},
			{SYSZ_REG_V25, i128},
			{SYSZ_REG_V26, i128},
			{SYSZ_REG_V27, i128},
			{SYSZ_REG_V28, i128},
			{SYSZ_REG_V29, i128},
			{SYSZ_REG_V30, i128},
			{SYSZ_REG_V31, i128},
	};

	// Capstone 6 names 64-bit GPRs R0D..R15D (compat: SYSZ_REG_0 == R0D).
	// R*L / R*H are aliased onto these in generateRegisters().
	for (uint32_t r = SYSZ_REG_R0D; r <= SYSZ_REG_R15D; ++r)
	{
		r2t[r] = i64;
	}
	for (uint32_t r = SYSZ_REG_F0D; r <= SYSZ_REG_F31D; ++r)
	{
		r2t[r] = f64;
	}
	for (uint32_t r = SYSZ_REG_F0S; r <= SYSZ_REG_F31S; ++r)
	{
		r2t[r] = f32;
	}

	_reg2type = std::move(r2t);
}

void Capstone2LlvmIrTranslatorSysz_impl::initializePseudoCallInstructionIDs()
{
	_callInsnIds = {
			SYSZ_INS_BASR,
			SYSZ_INS_BRAS,
			SYSZ_INS_BRASL,
	};

	_returnInsnIds = {
			// Returns are BR / BCR to r14; classified during translation.
	};

	_branchInsnIds = {
			SYSZ_INS_BR,
			SYSZ_INS_J,
			SYSZ_INS_J_G_LU_,
	};

	_condBranchInsnIds = {
			SYSZ_INS_BCR,
			SYSZ_INS_BRC,
			SYSZ_INS_BRCL,
			SYSZ_INS_JE,
			SYSZ_INS_J_G_L_E,
			SYSZ_INS_JH,
			SYSZ_INS_J_G_L_H,
			SYSZ_INS_JL,
			SYSZ_INS_J_G_L_L,
			SYSZ_INS_JNE,
			SYSZ_INS_J_G_L_NE,
			SYSZ_INS_JO,
			SYSZ_INS_J_G_L_O,
			SYSZ_INS_JNO,
			SYSZ_INS_J_G_L_NO,
			SYSZ_INS_JHE,
			SYSZ_INS_J_G_L_HE,
			SYSZ_INS_JLE,
			SYSZ_INS_J_G_L_LE,
			SYSZ_INS_JLH,
			SYSZ_INS_J_G_L_LH,
			SYSZ_INS_JNL,
			SYSZ_INS_J_G_L_NL,
			SYSZ_INS_JNH,
			SYSZ_INS_J_G_L_NH,
			SYSZ_INS_JNLE,
			SYSZ_INS_J_G_L_NLE,
			SYSZ_INS_JNHE,
			SYSZ_INS_J_G_L_NHE,
			SYSZ_INS_JNLH,
			SYSZ_INS_J_G_L_NLH,
			SYSZ_INS_JZ,
			SYSZ_INS_J_G_L_Z,
			SYSZ_INS_JNZ,
			SYSZ_INS_J_G_L_NZ,
			SYSZ_INS_JM,
			SYSZ_INS_J_G_L_M,
			SYSZ_INS_JP,
			SYSZ_INS_J_G_L_P,
	};

	_controlFlowInsnIds = {
			SYSZ_INS_BR,
			SYSZ_INS_BCR,
			SYSZ_INS_BRC,
			SYSZ_INS_BRCL,
			SYSZ_INS_BASR,
			SYSZ_INS_BRAS,
			SYSZ_INS_BRASL,
			SYSZ_INS_J,
			SYSZ_INS_J_G_LU_,
	};
}

std::map<std::size_t, void (Capstone2LlvmIrTranslatorSysz_impl::*)(cs_insn* i, cs_sysz*, llvm::IRBuilder<>&)>
	Capstone2LlvmIrTranslatorSysz_impl::_i2fm = {
		{SYSZ_INS_LR, &Capstone2LlvmIrTranslatorSysz_impl::translateLoadReg32},
		{SYSZ_INS_LGR, &Capstone2LlvmIrTranslatorSysz_impl::translateLoadReg64},
		{SYSZ_INS_AR, &Capstone2LlvmIrTranslatorSysz_impl::translateAdd32},
		{SYSZ_INS_AGR, &Capstone2LlvmIrTranslatorSysz_impl::translateAdd64},
		{SYSZ_INS_SR, &Capstone2LlvmIrTranslatorSysz_impl::translateSub32},
		{SYSZ_INS_SGR, &Capstone2LlvmIrTranslatorSysz_impl::translateSub64},
		{SYSZ_INS_NR, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical32},
		{SYSZ_INS_OR, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical32},
		{SYSZ_INS_XR, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical32},
		{SYSZ_INS_L, &Capstone2LlvmIrTranslatorSysz_impl::translateLoad32},
		{SYSZ_INS_LG, &Capstone2LlvmIrTranslatorSysz_impl::translateLoad64},
		{SYSZ_INS_ST, &Capstone2LlvmIrTranslatorSysz_impl::translateStore32},
		{SYSZ_INS_STG, &Capstone2LlvmIrTranslatorSysz_impl::translateStore64},
		{SYSZ_INS_LA, &Capstone2LlvmIrTranslatorSysz_impl::translateLa},
		{SYSZ_INS_BR, &Capstone2LlvmIrTranslatorSysz_impl::translateBr},
		{SYSZ_INS_BCR, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_BRC, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_BRCL, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_LU_, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_E, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JH, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_H, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JL, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_L, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JNE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_NE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JO, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_O, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JNO, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_NO, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JHE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_HE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JLE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_LE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JLH, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_LH, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JNL, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_NL, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JNH, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_NH, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JNLE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_NLE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JNHE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_NHE, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JNLH, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_NLH, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JZ, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_Z, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JNZ, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_NZ, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JM, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_M, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_JP, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_J_G_L_P, &Capstone2LlvmIrTranslatorSysz_impl::translateBrc},
		{SYSZ_INS_BASR, &Capstone2LlvmIrTranslatorSysz_impl::translateBasr},
		{SYSZ_INS_BRAS, &Capstone2LlvmIrTranslatorSysz_impl::translateBrasl},
		{SYSZ_INS_BRASL, &Capstone2LlvmIrTranslatorSysz_impl::translateBrasl},

		{SYSZ_INS_NGR, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical64},
		{SYSZ_INS_OGR, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical64},
		{SYSZ_INS_XGR, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical64},
		{SYSZ_INS_LGHI, &Capstone2LlvmIrTranslatorSysz_impl::translateImm64},
		{SYSZ_INS_LHI, &Capstone2LlvmIrTranslatorSysz_impl::translateImm64},
		{SYSZ_INS_AGHI, &Capstone2LlvmIrTranslatorSysz_impl::translateAddImm},
		{SYSZ_INS_AHI, &Capstone2LlvmIrTranslatorSysz_impl::translateAddImm},
		{SYSZ_INS_CR, &Capstone2LlvmIrTranslatorSysz_impl::translateCompare},
		{SYSZ_INS_CGR, &Capstone2LlvmIrTranslatorSysz_impl::translateCompare},
		{SYSZ_INS_CHI, &Capstone2LlvmIrTranslatorSysz_impl::translateCompare},
		{SYSZ_INS_CGHI, &Capstone2LlvmIrTranslatorSysz_impl::translateCompare},
		{SYSZ_INS_LGFR, &Capstone2LlvmIrTranslatorSysz_impl::translateExtend32},
		{SYSZ_INS_LLGFR, &Capstone2LlvmIrTranslatorSysz_impl::translateExtend32},
		{SYSZ_INS_LGF, &Capstone2LlvmIrTranslatorSysz_impl::translateExtend32},
		{SYSZ_INS_LLGF, &Capstone2LlvmIrTranslatorSysz_impl::translateExtend32},
		{SYSZ_INS_SLLG, &Capstone2LlvmIrTranslatorSysz_impl::translateShift64},
		{SYSZ_INS_SRLG, &Capstone2LlvmIrTranslatorSysz_impl::translateShift64},
		{SYSZ_INS_SRAG, &Capstone2LlvmIrTranslatorSysz_impl::translateShift64},
		{SYSZ_INS_LAY, &Capstone2LlvmIrTranslatorSysz_impl::translateLay},
		{SYSZ_INS_LARL, &Capstone2LlvmIrTranslatorSysz_impl::translateLay},
		{SYSZ_INS_LTGR, &Capstone2LlvmIrTranslatorSysz_impl::translateLoadReg64},
		{SYSZ_INS_LTR, &Capstone2LlvmIrTranslatorSysz_impl::translateLoadReg32},

		{SYSZ_INS_AEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_AEB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_ADBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_ADB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_SEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_SEB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_SDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_SDB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_MEEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_MEEB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_MDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_MDB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_DEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_DEB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_DDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_DDB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpArith},
		{SYSZ_INS_CEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpCompare},
		{SYSZ_INS_CEB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpCompare},
		{SYSZ_INS_CDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpCompare},
		{SYSZ_INS_CDB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpCompare},
		{SYSZ_INS_LE, &Capstone2LlvmIrTranslatorSysz_impl::translateFpLoad},
		{SYSZ_INS_LEY, &Capstone2LlvmIrTranslatorSysz_impl::translateFpLoad},
		{SYSZ_INS_LD, &Capstone2LlvmIrTranslatorSysz_impl::translateFpLoad},
		{SYSZ_INS_LDY, &Capstone2LlvmIrTranslatorSysz_impl::translateFpLoad},
		{SYSZ_INS_STE, &Capstone2LlvmIrTranslatorSysz_impl::translateFpStore},
		{SYSZ_INS_STEY, &Capstone2LlvmIrTranslatorSysz_impl::translateFpStore},
		{SYSZ_INS_STD, &Capstone2LlvmIrTranslatorSysz_impl::translateFpStore},
		{SYSZ_INS_STDY, &Capstone2LlvmIrTranslatorSysz_impl::translateFpStore},
		{SYSZ_INS_LER, &Capstone2LlvmIrTranslatorSysz_impl::translateFpMove},
		{SYSZ_INS_LDR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpMove},
		{SYSZ_INS_LDEB, &Capstone2LlvmIrTranslatorSysz_impl::translateLdeb},
		{SYSZ_INS_LDEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateLdeb},
		{SYSZ_INS_LEDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateLedbr},

		{SYSZ_INS_VL, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorLoad},
		{SYSZ_INS_VST, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorStore},
		{SYSZ_INS_VLR, &Capstone2LlvmIrTranslatorSysz_impl::translateVlr},
		{SYSZ_INS_VLREP, &Capstone2LlvmIrTranslatorSysz_impl::translateVlrep},
		{SYSZ_INS_VLREPB, &Capstone2LlvmIrTranslatorSysz_impl::translateVlrep},
		{SYSZ_INS_VLREPH, &Capstone2LlvmIrTranslatorSysz_impl::translateVlrep},
		{SYSZ_INS_VLREPF, &Capstone2LlvmIrTranslatorSysz_impl::translateVlrep},
		{SYSZ_INS_VLREPG, &Capstone2LlvmIrTranslatorSysz_impl::translateVlrep},
		{SYSZ_INS_VLEG, &Capstone2LlvmIrTranslatorSysz_impl::translateVleg},
		{SYSZ_INS_VLEF, &Capstone2LlvmIrTranslatorSysz_impl::translateVleg},
		{SYSZ_INS_VSTEG, &Capstone2LlvmIrTranslatorSysz_impl::translateVsteg},
		{SYSZ_INS_VSTEF, &Capstone2LlvmIrTranslatorSysz_impl::translateVsteg},

		{SYSZ_INS_MVC, &Capstone2LlvmIrTranslatorSysz_impl::translateSs},
		{SYSZ_INS_CLC, &Capstone2LlvmIrTranslatorSysz_impl::translateSs},
		{SYSZ_INS_XC, &Capstone2LlvmIrTranslatorSysz_impl::translateSs},
		{SYSZ_INS_NC, &Capstone2LlvmIrTranslatorSysz_impl::translateSs},
		{SYSZ_INS_OC, &Capstone2LlvmIrTranslatorSysz_impl::translateSs},
		{SYSZ_INS_MVCL, &Capstone2LlvmIrTranslatorSysz_impl::translateMvcl},

		{SYSZ_INS_LM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoadMultiple},
		{SYSZ_INS_LMG, &Capstone2LlvmIrTranslatorSysz_impl::translateLoadMultiple},
		{SYSZ_INS_STM, &Capstone2LlvmIrTranslatorSysz_impl::translateStoreMultiple},
		{SYSZ_INS_STMG, &Capstone2LlvmIrTranslatorSysz_impl::translateStoreMultiple},

		{SYSZ_INS_CS, &Capstone2LlvmIrTranslatorSysz_impl::translateCs},
		{SYSZ_INS_CSG, &Capstone2LlvmIrTranslatorSysz_impl::translateCs},
		{SYSZ_INS_CDS, &Capstone2LlvmIrTranslatorSysz_impl::translateCds},
		{SYSZ_INS_CDSG, &Capstone2LlvmIrTranslatorSysz_impl::translateCds},

		{SYSZ_INS_VA, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAQ, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VS, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VSB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VSH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VSF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VSG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VSQ, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VN, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VO, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VX, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VNC, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VNO, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VNN, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VOC, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCEQ, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCEQB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCEQH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCEQF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCEQG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},

		{SYSZ_INS_VML, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorMul},
		{SYSZ_INS_VMLB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorMul},
		{SYSZ_INS_VMLH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorMul},
		{SYSZ_INS_VMLF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorMul},
		{SYSZ_INS_VMH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorMul},
		{SYSZ_INS_VMHB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorMul},
		{SYSZ_INS_VMHH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorMul},
		{SYSZ_INS_VMHF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorMul},

		{SYSZ_INS_VPERM, &Capstone2LlvmIrTranslatorSysz_impl::translateVperm},
		{SYSZ_INS_VPDI, &Capstone2LlvmIrTranslatorSysz_impl::translateVpdi},

		{SYSZ_INS_VREP, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPB, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPH, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPF, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPG, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPI, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPIB, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPIH, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPIF, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},
		{SYSZ_INS_VREPIG, &Capstone2LlvmIrTranslatorSysz_impl::translateVrep},

		{SYSZ_INS_VPK, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKH, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKF, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKG, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKLS, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKLSH, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKLSF, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKLSG, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKS, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKSH, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKSF, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},
		{SYSZ_INS_VPKSG, &Capstone2LlvmIrTranslatorSysz_impl::translateVpk},

		{SYSZ_INS_VFA, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFASB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFADB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFS, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFSSB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFSDB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFM, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFMSB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFMDB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFD, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFDSB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFDDB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFCE, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFCESB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFCEDB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFCH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFCHSB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFCHDB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},

		{SYSZ_INS_CGEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CGEBRA, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CFEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CFEBRA, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CGDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CGDBRA, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CFDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CFDBRA, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CEGBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CEGBRA, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CDGBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_CDGBRA, &Capstone2LlvmIrTranslatorSysz_impl::translateFpConvert},
		{SYSZ_INS_SQEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpSqrt},
		{SYSZ_INS_SQDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpSqrt},
		{SYSZ_INS_MAEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpFma},
		{SYSZ_INS_MAEB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpFma},
		{SYSZ_INS_MADBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFpFma},
		{SYSZ_INS_MADB, &Capstone2LlvmIrTranslatorSysz_impl::translateFpFma},
		{SYSZ_INS_FIDBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFidbr},
		{SYSZ_INS_FIDBRA, &Capstone2LlvmIrTranslatorSysz_impl::translateFidbr},
		{SYSZ_INS_FIEBR, &Capstone2LlvmIrTranslatorSysz_impl::translateFidbr},
		{SYSZ_INS_FIEBRA, &Capstone2LlvmIrTranslatorSysz_impl::translateFidbr},

		{SYSZ_INS_AFI, &Capstone2LlvmIrTranslatorSysz_impl::translateAddImm},
		{SYSZ_INS_AGFI, &Capstone2LlvmIrTranslatorSysz_impl::translateAddImm},
		{SYSZ_INS_NG, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical64},
		{SYSZ_INS_OG, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical64},
		{SYSZ_INS_XG, &Capstone2LlvmIrTranslatorSysz_impl::translateLogical64},
		{SYSZ_INS_SLL, &Capstone2LlvmIrTranslatorSysz_impl::translateShift64},
		{SYSZ_INS_SRL, &Capstone2LlvmIrTranslatorSysz_impl::translateShift64},
		{SYSZ_INS_SRA, &Capstone2LlvmIrTranslatorSysz_impl::translateShift64},

		{SYSZ_INS_LOC, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCNZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCG, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGNZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGR, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRNZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGRZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCR, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRNZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCRZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},

		{SYSZ_INS_LOCHI, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHIE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHIH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHIHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHIL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHILE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHILH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHIM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHINZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHIO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHIP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCHIZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHI, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHIE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHIH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHIHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHIL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHILE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHILH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHIM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINHE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINL, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINLE, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINLH, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINM, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHINZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHIO, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHIP, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},
		{SYSZ_INS_LOCGHIZ, &Capstone2LlvmIrTranslatorSysz_impl::translateLoc},

		{SYSZ_INS_RISBG, &Capstone2LlvmIrTranslatorSysz_impl::translateRisbg},
		{SYSZ_INS_RISBGN, &Capstone2LlvmIrTranslatorSysz_impl::translateRisbg},

		{SYSZ_INS_LAA, &Capstone2LlvmIrTranslatorSysz_impl::translateLaa},
		{SYSZ_INS_LAAG, &Capstone2LlvmIrTranslatorSysz_impl::translateLaa},
		{SYSZ_INS_LAN, &Capstone2LlvmIrTranslatorSysz_impl::translateLaa},
		{SYSZ_INS_LANG, &Capstone2LlvmIrTranslatorSysz_impl::translateLaa},
		{SYSZ_INS_LAO, &Capstone2LlvmIrTranslatorSysz_impl::translateLaa},
		{SYSZ_INS_LAOG, &Capstone2LlvmIrTranslatorSysz_impl::translateLaa},
		{SYSZ_INS_LAX, &Capstone2LlvmIrTranslatorSysz_impl::translateLaa},
		{SYSZ_INS_LAXG, &Capstone2LlvmIrTranslatorSysz_impl::translateLaa},

		{SYSZ_INS_VFMA, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFMADB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},
		{SYSZ_INS_VFMASB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorFpArith},

		{SYSZ_INS_VSEL, &Capstone2LlvmIrTranslatorSysz_impl::translateVsel},

		{SYSZ_INS_VESL, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLV, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLVB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLVH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLVF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESLVG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRA, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAV, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAVB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAVH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAVF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRAVG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRL, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLV, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLVB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLVH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLVF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},
		{SYSZ_INS_VESRLVG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorShift},

		{SYSZ_INS_VLC, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLCB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLCH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLCF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLCG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLP, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLPB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLPH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLPF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},
		{SYSZ_INS_VLPG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorUnary},

		{SYSZ_INS_VAVG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGL, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGLB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGLH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGLF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VAVGLG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},

		{SYSZ_INS_VCH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCHB, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCHH, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCHF, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},
		{SYSZ_INS_VCHG, &Capstone2LlvmIrTranslatorSysz_impl::translateVectorArith},

		{SYSZ_INS_VLLEZ, &Capstone2LlvmIrTranslatorSysz_impl::translateVllez},
		{SYSZ_INS_VLLEZB, &Capstone2LlvmIrTranslatorSysz_impl::translateVllez},
		{SYSZ_INS_VLLEZH, &Capstone2LlvmIrTranslatorSysz_impl::translateVllez},
		{SYSZ_INS_VLLEZF, &Capstone2LlvmIrTranslatorSysz_impl::translateVllez},
		{SYSZ_INS_VLLEZG, &Capstone2LlvmIrTranslatorSysz_impl::translateVllez},
		{SYSZ_INS_VLLEZLF, &Capstone2LlvmIrTranslatorSysz_impl::translateVllez},

		{SYSZ_INS_VGEF, &Capstone2LlvmIrTranslatorSysz_impl::translateVgef},
		{SYSZ_INS_VGEG, &Capstone2LlvmIrTranslatorSysz_impl::translateVgef},
		{SYSZ_INS_VSCEF, &Capstone2LlvmIrTranslatorSysz_impl::translateVgef},
		{SYSZ_INS_VSCEG, &Capstone2LlvmIrTranslatorSysz_impl::translateVgef},

		{SYSZ_INS_VGBM, &Capstone2LlvmIrTranslatorSysz_impl::translateVgbm},
		{SYSZ_INS_VONE, &Capstone2LlvmIrTranslatorSysz_impl::translateVgbm},
		{SYSZ_INS_VZERO, &Capstone2LlvmIrTranslatorSysz_impl::translateVgbm},

		{SYSZ_INS_VGM, &Capstone2LlvmIrTranslatorSysz_impl::translateVgm},
		{SYSZ_INS_VGMB, &Capstone2LlvmIrTranslatorSysz_impl::translateVgm},
		{SYSZ_INS_VGMH, &Capstone2LlvmIrTranslatorSysz_impl::translateVgm},
		{SYSZ_INS_VGMF, &Capstone2LlvmIrTranslatorSysz_impl::translateVgm},
		{SYSZ_INS_VGMG, &Capstone2LlvmIrTranslatorSysz_impl::translateVgm},

		{SYSZ_INS_VLEIB, &Capstone2LlvmIrTranslatorSysz_impl::translateVlei},
		{SYSZ_INS_VLEIH, &Capstone2LlvmIrTranslatorSysz_impl::translateVlei},
		{SYSZ_INS_VLEIF, &Capstone2LlvmIrTranslatorSysz_impl::translateVlei},
		{SYSZ_INS_VLEIG, &Capstone2LlvmIrTranslatorSysz_impl::translateVlei},

		{SYSZ_INS_VFEE, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEB, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEH, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEF, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEBS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEHS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEFS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEZB, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEZH, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEZF, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEZBS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEZHS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFEEZFS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENE, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEB, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEH, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEF, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEBS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEHS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEFS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEZB, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEZH, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEZF, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEZBS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEZHS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},
		{SYSZ_INS_VFENEZFS, &Capstone2LlvmIrTranslatorSysz_impl::translateVfee},

		{SYSZ_INS_VUPH, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPHB, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPHH, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPHF, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPL, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLB, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLHW, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLF, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLH, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLHB, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLHH, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLHF, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLL, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLLB, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLLH, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},
		{SYSZ_INS_VUPLLF, &Capstone2LlvmIrTranslatorSysz_impl::translateVupk},

		{SYSZ_INS_VSEG, &Capstone2LlvmIrTranslatorSysz_impl::translateVseg},
		{SYSZ_INS_VSEGB, &Capstone2LlvmIrTranslatorSysz_impl::translateVseg},
		{SYSZ_INS_VSEGH, &Capstone2LlvmIrTranslatorSysz_impl::translateVseg},
		{SYSZ_INS_VSEGF, &Capstone2LlvmIrTranslatorSysz_impl::translateVseg},
};

} // namespace capstone2llvmir
} // namespace retdec
