/**
 * @file src/py_emitter/py_file_emitter.cpp
 */

#include "retdec/py_emitter/py_file_emitter.h"
#include "retdec/py_emitter/py_expr_emitter.h"
#include "retdec/py_emitter/py_stmt_emitter.h"
#include "retdec/py_emitter/py_writer.h"
#include <algorithm>

#include <sstream>

namespace retdec {
namespace py_emitter {

PyFileEmitter::PyFileEmitter(PyEmitOptions opts) : opts_(std::move(opts)) {}

// ─── fileHeader ──────────────────────────────────────────────────────────────

std::string PyFileEmitter::fileHeader(const PyModule& mod) const {
    std::ostringstream ss;
    ss << "# Auto-generated by RetDec Python decompiler\n";
    if (!mod.filename.empty())
        ss << "# Source: " << mod.filename << "\n";
    ss << "# Python " << mod.pythonMajor << "." << mod.pythonMinor << "\n";
    ss << "\n";
    return ss.str();
}

// ─── futureImports ───────────────────────────────────────────────────────────

std::string PyFileEmitter::futureImports() const {
    // For Python 3.9-, emit annotations to allow postponed evaluation
    if (opts_.pyMajor == 3 && opts_.pyMinor < 10)
        return "from __future__ import annotations\n\n";
    return "";
}

// ─── emit ────────────────────────────────────────────────────────────────────

PyEmitResult PyFileEmitter::emit(const PyModule& module) const {
    PyEmitResult result;

    PyWriter writer;
    PyExprEmitter exprEmitter(writer);
    PyStmtEmitter::Options stmtOpts;
    stmtOpts.pyMajor = opts_.pyMajor;
    stmtOpts.pyMinor = opts_.pyMinor;
    PyStmtEmitter stmtEmitter(writer, exprEmitter, stmtOpts);

    std::ostringstream out;

    if (opts_.emitFileHeader)
        out << fileHeader(module);

    if (opts_.emitFutureImports)
        out << futureImports();

    // Separate imports from other statements
    StmtList imports;
    StmtList other;
    for (const auto& s : module.body) {
        if (!s) continue;
        if (s->kind == PyStmt::Kind::Import || s->kind == PyStmt::Kind::ImportFrom)
            imports.push_back(s);
        else
            other.push_back(s);
    }

    // Emit imports first (sorted if requested)
    if (opts_.sortImports && !imports.empty()) {
        std::sort(imports.begin(), imports.end(), [](const PyStmtPtr& a, const PyStmtPtr& b) {
            std::string na = a->module.has_value() ? *a->module : (a->aliases.empty() ? "" : a->aliases[0].name);
            std::string nb = b->module.has_value() ? *b->module : (b->aliases.empty() ? "" : b->aliases[0].name);
            return na < nb;
        });
    }
    stmtEmitter.emitBody(imports);
    if (!imports.empty() && !other.empty())
        writer.blank();

    // Emit the rest with blank lines between top-level defs
    int blanksBetween = opts_.blankLinesBetweenTopLevel;
    for (size_t i = 0; i < other.size(); ++i) {
        const auto& s = other[i];
        bool isTopLevelDef = (s->kind == PyStmt::Kind::FunctionDef ||
                               s->kind == PyStmt::Kind::AsyncFunctionDef ||
                               s->kind == PyStmt::Kind::ClassDef);
        bool prevIsDef = i > 0 && (other[i-1]->kind == PyStmt::Kind::FunctionDef ||
                                    other[i-1]->kind == PyStmt::Kind::AsyncFunctionDef ||
                                    other[i-1]->kind == PyStmt::Kind::ClassDef);
        if (i > 0 && (isTopLevelDef || prevIsDef)) {
            for (int b = 0; b < blanksBetween; ++b)
                writer.blank();
        }
        stmtEmitter.emitStmt(*s);
    }

    out << writer.str();

    result.source = out.str();
    return result;
}

} // namespace py_emitter
} // namespace retdec
