/**
 * @file include/retdec/py_emitter/py_file_emitter.h
 * @brief Top-level Python file emitter: PyModule → .py source string.
 *
 * Produces:
 *   - Auto-generated file header comment
 *   - Version-appropriate encoding declaration (omitted for UTF-8 default)
 *   - from __future__ imports for version compatibility
 *   - Module body (imports, classes, functions, top-level code)
 *   - 88-char line length, 4-space indentation (Black-compatible)
 */

#ifndef RETDEC_PY_EMITTER_PY_FILE_EMITTER_H
#define RETDEC_PY_EMITTER_PY_FILE_EMITTER_H

#include "retdec/py_reconstruct/py_ast_nodes.h"

#include <string>

namespace retdec {
namespace py_emitter {

using namespace py_reconstruct;

struct PyEmitOptions {
    int  pyMajor        = 3;
    int  pyMinor        = 10;
    bool emitFileHeader = true;    ///< Emit "# Auto-generated by RetDec" comment
    bool emitFutureImports = false;///< Emit from __future__ imports
    bool sortImports    = true;    ///< Sort import statements alphabetically
    int  blankLinesBetweenTopLevel = 2; ///< PEP 8: 2 blank lines between top-level defs
};

struct PyEmitResult {
    std::string source;
    std::vector<std::string> warnings;
};

class PyFileEmitter {
public:
    explicit PyFileEmitter(PyEmitOptions opts = PyEmitOptions{});

    /// Emit an entire PyModule to a Python source string.
    PyEmitResult emit(const PyModule& module) const;

private:
    PyEmitOptions opts_;

    std::string fileHeader(const PyModule& mod) const;
    std::string futureImports() const;
};

} // namespace py_emitter
} // namespace retdec

#endif // RETDEC_PY_EMITTER_PY_FILE_EMITTER_H
