/**
 * @file src/capstone2llvmir/riscv/riscv_init.cpp
 * @brief Initializations for RISC-V implementation of @c Capstone2LlvmIrTranslator.
 * @copyright (c) 2025-2026 Odin Loch trading as Imortek
 */

#include "capstone2llvmir/riscv/riscv_impl.h"

namespace retdec {
namespace capstone2llvmir {

//
//==============================================================================
// Pure virtual methods from Capstone2LlvmIrTranslator_impl
//==============================================================================
//

void Capstone2LlvmIrTranslatorRiscv_impl::initializeArchSpecific()
{
	// Capstone 6 auto-sync RISC-V defaults to alias operand layouts
	// (jal/frflags/nop). Prefer the real ADDI/JAL/CSRRS details.
	cs_option(
			_handle,
			CS_OPT_DETAIL,
			static_cast<size_t>(CS_OPT_ON) | static_cast<size_t>(CS_OPT_DETAIL_REAL));
}

namespace {

uint32_t csrLlvmRegId(uint16_t encoding)
{
	return static_cast<uint32_t>(RISCV_REG_ENDING) + 0x1000u + encoding;
}

} // namespace

void Capstone2LlvmIrTranslatorRiscv_impl::initializeRegNameMap()
{
	std::map<uint32_t, std::string> r2n = {
		{RISCV_REG_PC, "pc"},
		{RISCV_REG_FFLAGS, "fflags"},
		{RISCV_REG_FRM, "frm"},
		{RISCV_REG_VL, "vl"},
		{RISCV_REG_VTYPE, "vtype"},
		{RISCV_REG_VLENB, "vlenb"},
		{RISCV_REG_VXSAT, "vxsat"},
		{RISCV_REG_VXRM, "vxrm"},
		{csrLlvmRegId(RISCV_SYSREG_CYCLE), "cycle"},
		{csrLlvmRegId(RISCV_SYSREG_TIME), "time"},
		{csrLlvmRegId(RISCV_SYSREG_INSTRET), "instret"},
		{csrLlvmRegId(RISCV_SYSREG_CYCLEH), "cycleh"},
		{csrLlvmRegId(RISCV_SYSREG_TIMEH), "timeh"},
		{csrLlvmRegId(RISCV_SYSREG_INSTRETH), "instreth"},
		{csrLlvmRegId(RISCV_SYSREG_SSTATUS), "sstatus"},
		{csrLlvmRegId(RISCV_SYSREG_SIE), "sie"},
		{csrLlvmRegId(RISCV_SYSREG_STVEC), "stvec"},
		{csrLlvmRegId(RISCV_SYSREG_SSCRATCH), "sscratch"},
		{csrLlvmRegId(RISCV_SYSREG_SEPC), "sepc"},
		{csrLlvmRegId(RISCV_SYSREG_SCAUSE), "scause"},
		{csrLlvmRegId(RISCV_SYSREG_STVAL), "stval"},
		{csrLlvmRegId(RISCV_SYSREG_SIP), "sip"},
		{csrLlvmRegId(RISCV_SYSREG_SATP), "satp"},
		{csrLlvmRegId(RISCV_SYSREG_MSTATUS), "mstatus"},
		{csrLlvmRegId(RISCV_SYSREG_MISA), "misa"},
		{csrLlvmRegId(RISCV_SYSREG_MEDELEG), "medeleg"},
		{csrLlvmRegId(RISCV_SYSREG_MIDELEG), "mideleg"},
		{csrLlvmRegId(RISCV_SYSREG_MIE), "mie"},
		{csrLlvmRegId(RISCV_SYSREG_MTVEC), "mtvec"},
		{csrLlvmRegId(RISCV_SYSREG_MSCRATCH), "mscratch"},
		{csrLlvmRegId(RISCV_SYSREG_MEPC), "mepc"},
		{csrLlvmRegId(RISCV_SYSREG_MCAUSE), "mcause"},
		{csrLlvmRegId(RISCV_SYSREG_MTVAL), "mtval"},
		{csrLlvmRegId(RISCV_SYSREG_MIP), "mip"},
		{csrLlvmRegId(RISCV_SYSREG_MHARTID), "mhartid"},
		{csrLlvmRegId(RISCV_SYSREG_MVENDORID), "mvendorid"},
		{csrLlvmRegId(RISCV_SYSREG_MARCHID), "marchid"},
		{csrLlvmRegId(RISCV_SYSREG_MIMPID), "mimpid"},
	};

	_reg2name = std::move(r2n);
}

void Capstone2LlvmIrTranslatorRiscv_impl::initializeRegTypeMap()
{
	auto* f32 = llvm::Type::getFloatTy(_module->getContext());
	auto* f64 = llvm::Type::getDoubleTy(_module->getContext());
	auto* defTy = getDefaultType();

	std::map<uint32_t, llvm::Type*> r2t = {
		{RISCV_REG_PC, defTy},

		{RISCV_REG_X0, defTy},
		{RISCV_REG_X1, defTy},
		{RISCV_REG_X2, defTy},
		{RISCV_REG_X3, defTy},
		{RISCV_REG_X4, defTy},
		{RISCV_REG_X5, defTy},
		{RISCV_REG_X6, defTy},
		{RISCV_REG_X7, defTy},
		{RISCV_REG_X8, defTy},
		{RISCV_REG_X9, defTy},
		{RISCV_REG_X10, defTy},
		{RISCV_REG_X11, defTy},
		{RISCV_REG_X12, defTy},
		{RISCV_REG_X13, defTy},
		{RISCV_REG_X14, defTy},
		{RISCV_REG_X15, defTy},
		{RISCV_REG_X16, defTy},
		{RISCV_REG_X17, defTy},
		{RISCV_REG_X18, defTy},
		{RISCV_REG_X19, defTy},
		{RISCV_REG_X20, defTy},
		{RISCV_REG_X21, defTy},
		{RISCV_REG_X22, defTy},
		{RISCV_REG_X23, defTy},
		{RISCV_REG_X24, defTy},
		{RISCV_REG_X25, defTy},
		{RISCV_REG_X26, defTy},
		{RISCV_REG_X27, defTy},
		{RISCV_REG_X28, defTy},
		{RISCV_REG_X29, defTy},
		{RISCV_REG_X30, defTy},
		{RISCV_REG_X31, defTy},

		{RISCV_REG_FFLAGS, defTy},
		{RISCV_REG_FRM, defTy},
		{RISCV_REG_VL, defTy},
		{RISCV_REG_VTYPE, defTy},
		{RISCV_REG_VLENB, defTy},
		{RISCV_REG_VXSAT, defTy},
		{RISCV_REG_VXRM, defTy},

		{csrLlvmRegId(RISCV_SYSREG_CYCLE), defTy},
		{csrLlvmRegId(RISCV_SYSREG_TIME), defTy},
		{csrLlvmRegId(RISCV_SYSREG_INSTRET), defTy},
		{csrLlvmRegId(RISCV_SYSREG_CYCLEH), defTy},
		{csrLlvmRegId(RISCV_SYSREG_TIMEH), defTy},
		{csrLlvmRegId(RISCV_SYSREG_INSTRETH), defTy},
		{csrLlvmRegId(RISCV_SYSREG_SSTATUS), defTy},
		{csrLlvmRegId(RISCV_SYSREG_SIE), defTy},
		{csrLlvmRegId(RISCV_SYSREG_STVEC), defTy},
		{csrLlvmRegId(RISCV_SYSREG_SSCRATCH), defTy},
		{csrLlvmRegId(RISCV_SYSREG_SEPC), defTy},
		{csrLlvmRegId(RISCV_SYSREG_SCAUSE), defTy},
		{csrLlvmRegId(RISCV_SYSREG_STVAL), defTy},
		{csrLlvmRegId(RISCV_SYSREG_SIP), defTy},
		{csrLlvmRegId(RISCV_SYSREG_SATP), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MSTATUS), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MISA), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MEDELEG), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MIDELEG), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MIE), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MTVEC), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MSCRATCH), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MEPC), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MCAUSE), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MTVAL), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MIP), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MHARTID), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MVENDORID), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MARCHID), defTy},
		{csrLlvmRegId(RISCV_SYSREG_MIMPID), defTy},

		{RISCV_REG_F0_32, f32},
		{RISCV_REG_F1_32, f32},
		{RISCV_REG_F2_32, f32},
		{RISCV_REG_F3_32, f32},
		{RISCV_REG_F4_32, f32},
		{RISCV_REG_F5_32, f32},
		{RISCV_REG_F6_32, f32},
		{RISCV_REG_F7_32, f32},
		{RISCV_REG_F8_32, f32},
		{RISCV_REG_F9_32, f32},
		{RISCV_REG_F10_32, f32},
		{RISCV_REG_F11_32, f32},
		{RISCV_REG_F12_32, f32},
		{RISCV_REG_F13_32, f32},
		{RISCV_REG_F14_32, f32},
		{RISCV_REG_F15_32, f32},
		{RISCV_REG_F16_32, f32},
		{RISCV_REG_F17_32, f32},
		{RISCV_REG_F18_32, f32},
		{RISCV_REG_F19_32, f32},
		{RISCV_REG_F20_32, f32},
		{RISCV_REG_F21_32, f32},
		{RISCV_REG_F22_32, f32},
		{RISCV_REG_F23_32, f32},
		{RISCV_REG_F24_32, f32},
		{RISCV_REG_F25_32, f32},
		{RISCV_REG_F26_32, f32},
		{RISCV_REG_F27_32, f32},
		{RISCV_REG_F28_32, f32},
		{RISCV_REG_F29_32, f32},
		{RISCV_REG_F30_32, f32},
		{RISCV_REG_F31_32, f32},

		{RISCV_REG_F0_64, f64},
		{RISCV_REG_F1_64, f64},
		{RISCV_REG_F2_64, f64},
		{RISCV_REG_F3_64, f64},
		{RISCV_REG_F4_64, f64},
		{RISCV_REG_F5_64, f64},
		{RISCV_REG_F6_64, f64},
		{RISCV_REG_F7_64, f64},
		{RISCV_REG_F8_64, f64},
		{RISCV_REG_F9_64, f64},
		{RISCV_REG_F10_64, f64},
		{RISCV_REG_F11_64, f64},
		{RISCV_REG_F12_64, f64},
		{RISCV_REG_F13_64, f64},
		{RISCV_REG_F14_64, f64},
		{RISCV_REG_F15_64, f64},
		{RISCV_REG_F16_64, f64},
		{RISCV_REG_F17_64, f64},
		{RISCV_REG_F18_64, f64},
		{RISCV_REG_F19_64, f64},
		{RISCV_REG_F20_64, f64},
		{RISCV_REG_F21_64, f64},
		{RISCV_REG_F22_64, f64},
		{RISCV_REG_F23_64, f64},
		{RISCV_REG_F24_64, f64},
		{RISCV_REG_F25_64, f64},
		{RISCV_REG_F26_64, f64},
		{RISCV_REG_F27_64, f64},
		{RISCV_REG_F28_64, f64},
		{RISCV_REG_F29_64, f64},
		{RISCV_REG_F30_64, f64},
		{RISCV_REG_F31_64, f64},
	};

	_reg2type = std::move(r2t);
}

void Capstone2LlvmIrTranslatorRiscv_impl::initializePseudoCallInstructionIDs()
{
	_callInsnIds =
	{
			RISCV_INS_JAL,
			RISCV_INS_JALR,
			RISCV_INS_C_JAL,
			RISCV_INS_C_JALR,
			RISCV_INS_ECALL,
	};

	_returnInsnIds =
	{
			// jalr x0, ra, 0 is classified at translation time.
	};

	_branchInsnIds =
	{
			RISCV_INS_C_J,
			RISCV_INS_C_JR,
	};

	_condBranchInsnIds =
	{
			RISCV_INS_BEQ,
			RISCV_INS_BNE,
			RISCV_INS_BLT,
			RISCV_INS_BGE,
			RISCV_INS_BLTU,
			RISCV_INS_BGEU,
			RISCV_INS_C_BEQZ,
			RISCV_INS_C_BNEZ,
	};

	_controlFlowInsnIds =
	{
			RISCV_INS_JAL,
			RISCV_INS_JALR,
	};
}

//
//==============================================================================
// Instruction translation map initialization.
//==============================================================================
//

std::map<std::size_t, void (Capstone2LlvmIrTranslatorRiscv_impl::*)(cs_insn* i, cs_riscv*, llvm::IRBuilder<>&)>
	Capstone2LlvmIrTranslatorRiscv_impl::_i2fm = {
		{RISCV_INS_INVALID, nullptr},

		{RISCV_INS_ADD, &Capstone2LlvmIrTranslatorRiscv_impl::translateAdd},
		{RISCV_INS_ADDI, &Capstone2LlvmIrTranslatorRiscv_impl::translateAdd},
		{RISCV_INS_ADDIW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_ADDW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_ADD_UW, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
		{RISCV_INS_AMOADD_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOADD_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOADD_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOADD_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOADD_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOADD_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOADD_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOADD_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOAND_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOAND_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOAND_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOAND_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOAND_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOAND_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOAND_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOAND_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAXU_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAXU_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAXU_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAXU_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAXU_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAXU_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAXU_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAXU_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAX_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAX_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAX_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAX_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAX_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAX_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAX_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMAX_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMINU_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMINU_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMINU_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMINU_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMINU_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMINU_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMINU_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMINU_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMIN_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMIN_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMIN_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMIN_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMIN_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMIN_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMIN_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOMIN_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOOR_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOOR_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOOR_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOOR_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOOR_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOOR_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOOR_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOOR_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOSWAP_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOSWAP_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOSWAP_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOSWAP_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOSWAP_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOSWAP_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOSWAP_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOSWAP_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOXOR_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOXOR_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOXOR_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOXOR_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOXOR_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOXOR_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOXOR_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AMOXOR_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateAmo},
		{RISCV_INS_AND, &Capstone2LlvmIrTranslatorRiscv_impl::translateAnd},
		{RISCV_INS_ANDI, &Capstone2LlvmIrTranslatorRiscv_impl::translateAnd},
		{RISCV_INS_ANDN, &Capstone2LlvmIrTranslatorRiscv_impl::translateAndn},
		{RISCV_INS_AUIPC, &Capstone2LlvmIrTranslatorRiscv_impl::translateAuipc},
		{RISCV_INS_BEQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_BGE, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_BGEU, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_BLT, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_BLTU, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_BNE, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_BCLR, &Capstone2LlvmIrTranslatorRiscv_impl::translateZbs},
		{RISCV_INS_BCLRI, &Capstone2LlvmIrTranslatorRiscv_impl::translateZbs},
		{RISCV_INS_BEXT, &Capstone2LlvmIrTranslatorRiscv_impl::translateZbs},
		{RISCV_INS_BEXTI, &Capstone2LlvmIrTranslatorRiscv_impl::translateZbs},
		{RISCV_INS_BINV, &Capstone2LlvmIrTranslatorRiscv_impl::translateZbs},
		{RISCV_INS_BINVI, &Capstone2LlvmIrTranslatorRiscv_impl::translateZbs},
		{RISCV_INS_BSET, &Capstone2LlvmIrTranslatorRiscv_impl::translateZbs},
		{RISCV_INS_BSETI, &Capstone2LlvmIrTranslatorRiscv_impl::translateZbs},
		{RISCV_INS_BREV8, &Capstone2LlvmIrTranslatorRiscv_impl::translateBrev8},
		{RISCV_INS_CSRRC, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_CSRRCI, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_CSRRS, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_CSRRSI, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_CSRRW, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_CSRRWI, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_C_ADD, &Capstone2LlvmIrTranslatorRiscv_impl::translateAdd},
		{RISCV_INS_C_ADDI, &Capstone2LlvmIrTranslatorRiscv_impl::translateAdd},
		{RISCV_INS_C_ADDI16SP, &Capstone2LlvmIrTranslatorRiscv_impl::translateAdd},
		{RISCV_INS_C_ADDI4SPN, &Capstone2LlvmIrTranslatorRiscv_impl::translateAdd},
		{RISCV_INS_C_ADDIW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_C_ADDW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_C_AND, &Capstone2LlvmIrTranslatorRiscv_impl::translateAnd},
		{RISCV_INS_C_ANDI, &Capstone2LlvmIrTranslatorRiscv_impl::translateAnd},
		{RISCV_INS_C_BEQZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_C_BNEZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_C_EBREAK, &Capstone2LlvmIrTranslatorRiscv_impl::translateNop},
		{RISCV_INS_C_FLD, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpLoad},
		{RISCV_INS_C_FLDSP, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpLoad},
		{RISCV_INS_C_FLW, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpLoad},
		{RISCV_INS_C_FLWSP, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpLoad},
		{RISCV_INS_C_FSD, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpStore},
		{RISCV_INS_C_FSDSP, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpStore},
		{RISCV_INS_C_FSW, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpStore},
		{RISCV_INS_C_FSWSP, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpStore},
		{RISCV_INS_C_J, &Capstone2LlvmIrTranslatorRiscv_impl::translateJal},
		{RISCV_INS_C_JAL, &Capstone2LlvmIrTranslatorRiscv_impl::translateJal},
		{RISCV_INS_C_JALR, &Capstone2LlvmIrTranslatorRiscv_impl::translateJalr},
		{RISCV_INS_C_JR, &Capstone2LlvmIrTranslatorRiscv_impl::translateJalr},
		{RISCV_INS_C_LBU, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_C_LD, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_C_LDSP, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_C_LH, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_C_LHU, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_C_LI, &Capstone2LlvmIrTranslatorRiscv_impl::translateLi},
		{RISCV_INS_C_LUI, &Capstone2LlvmIrTranslatorRiscv_impl::translateLui},
		{RISCV_INS_C_LW, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_C_LWSP, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_C_MV, &Capstone2LlvmIrTranslatorRiscv_impl::translateMv},
		{RISCV_INS_C_MUL, &Capstone2LlvmIrTranslatorRiscv_impl::translateMul},
		{RISCV_INS_C_NOP, &Capstone2LlvmIrTranslatorRiscv_impl::translateNop},
		{RISCV_INS_C_NOT, &Capstone2LlvmIrTranslatorRiscv_impl::translateAndn},
		{RISCV_INS_C_OR, &Capstone2LlvmIrTranslatorRiscv_impl::translateOr},
		{RISCV_INS_C_SB, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_C_SD, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_C_SDSP, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_C_SEXT_B, &Capstone2LlvmIrTranslatorRiscv_impl::translateSextZext},
		{RISCV_INS_C_SEXT_H, &Capstone2LlvmIrTranslatorRiscv_impl::translateSextZext},
		{RISCV_INS_C_SH, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_C_SLLI, &Capstone2LlvmIrTranslatorRiscv_impl::translateSll},
		{RISCV_INS_C_SRAI, &Capstone2LlvmIrTranslatorRiscv_impl::translateSra},
		{RISCV_INS_C_SRLI, &Capstone2LlvmIrTranslatorRiscv_impl::translateSrl},
		{RISCV_INS_C_SUB, &Capstone2LlvmIrTranslatorRiscv_impl::translateSub},
		{RISCV_INS_C_SUBW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_C_SW, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_C_SWSP, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_C_UNIMP, &Capstone2LlvmIrTranslatorRiscv_impl::translateNop},
		{RISCV_INS_C_XOR, &Capstone2LlvmIrTranslatorRiscv_impl::translateXor},
		{RISCV_INS_C_ZEXT_B, &Capstone2LlvmIrTranslatorRiscv_impl::translateAnd},
		{RISCV_INS_C_ZEXT_H, &Capstone2LlvmIrTranslatorRiscv_impl::translateSextZext},
		{RISCV_INS_C_ZEXT_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
		{RISCV_INS_CLZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBitCount},
		{RISCV_INS_CLZW, &Capstone2LlvmIrTranslatorRiscv_impl::translateBitCount},
		{RISCV_INS_CPOP, &Capstone2LlvmIrTranslatorRiscv_impl::translateBitCount},
		{RISCV_INS_CPOPW, &Capstone2LlvmIrTranslatorRiscv_impl::translateBitCount},
		{RISCV_INS_CTZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBitCount},
		{RISCV_INS_CTZW, &Capstone2LlvmIrTranslatorRiscv_impl::translateBitCount},
		{RISCV_INS_CZERO_EQZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateCzero},
		{RISCV_INS_CZERO_NEZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateCzero},
		{RISCV_INS_DIV, &Capstone2LlvmIrTranslatorRiscv_impl::translateDiv},
		{RISCV_INS_DIVU, &Capstone2LlvmIrTranslatorRiscv_impl::translateDiv},
		{RISCV_INS_DIVUW, &Capstone2LlvmIrTranslatorRiscv_impl::translateDiv},
		{RISCV_INS_DIVW, &Capstone2LlvmIrTranslatorRiscv_impl::translateDiv},
		{RISCV_INS_EBREAK, &Capstone2LlvmIrTranslatorRiscv_impl::translateNop},
		{RISCV_INS_ECALL, &Capstone2LlvmIrTranslatorRiscv_impl::translateEcall},
		{RISCV_INS_FADD_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpArith},
		{RISCV_INS_FADD_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpArith},
		{RISCV_INS_FCLASS_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFclass},
		{RISCV_INS_FCLASS_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFclass},
		{RISCV_INS_FCVT_D_L, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_D_LU, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_D_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_D_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_D_WU, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_LU_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_LU_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_L_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_L_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_S_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_S_L, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_S_LU, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_S_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_S_WU, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_WU_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_WU_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_W_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FCVT_W_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcvt},
		{RISCV_INS_FDIV_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpArith},
		{RISCV_INS_FDIV_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpArith},
		{RISCV_INS_FENCE, &Capstone2LlvmIrTranslatorRiscv_impl::translateFence},
		{RISCV_INS_FENCE_I, &Capstone2LlvmIrTranslatorRiscv_impl::translateFence},
		{RISCV_INS_FENCE_TSO, &Capstone2LlvmIrTranslatorRiscv_impl::translateFence},
		{RISCV_INS_FEQ_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcmp},
		{RISCV_INS_FEQ_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcmp},
		{RISCV_INS_FLD, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpLoad},
		{RISCV_INS_FLE_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcmp},
		{RISCV_INS_FLE_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcmp},
		{RISCV_INS_FLT_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcmp},
		{RISCV_INS_FLT_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFcmp},
		{RISCV_INS_FLW, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpLoad},
		{RISCV_INS_FMADD_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpFma},
		{RISCV_INS_FMADD_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpFma},
		{RISCV_INS_FMAX_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFminMax},
		{RISCV_INS_FMAX_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFminMax},
		{RISCV_INS_FMIN_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFminMax},
		{RISCV_INS_FMIN_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFminMax},
		{RISCV_INS_FMSUB_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpFma},
		{RISCV_INS_FMSUB_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpFma},
		{RISCV_INS_FMUL_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpArith},
		{RISCV_INS_FMUL_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpArith},
		{RISCV_INS_FMV_D_X, &Capstone2LlvmIrTranslatorRiscv_impl::translateFmv},
		{RISCV_INS_FMV_W_X, &Capstone2LlvmIrTranslatorRiscv_impl::translateFmv},
		{RISCV_INS_FMV_X_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFmv},
		{RISCV_INS_FMV_X_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateFmv},
		{RISCV_INS_FNMADD_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpFma},
		{RISCV_INS_FNMADD_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpFma},
		{RISCV_INS_FNMSUB_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpFma},
		{RISCV_INS_FNMSUB_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpFma},
		{RISCV_INS_FSD, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpStore},
		{RISCV_INS_FSGNJN_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFsgnj},
		{RISCV_INS_FSGNJN_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFsgnj},
		{RISCV_INS_FSGNJX_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFsgnj},
		{RISCV_INS_FSGNJX_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFsgnj},
		{RISCV_INS_FSGNJ_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFsgnj},
		{RISCV_INS_FSGNJ_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFsgnj},
		{RISCV_INS_FSQRT_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFsqrt},
		{RISCV_INS_FSQRT_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFsqrt},
		{RISCV_INS_FSUB_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpArith},
		{RISCV_INS_FSUB_S, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpArith},
		{RISCV_INS_FSW, &Capstone2LlvmIrTranslatorRiscv_impl::translateFpStore},
		{RISCV_INS_JAL, &Capstone2LlvmIrTranslatorRiscv_impl::translateJal},
		{RISCV_INS_JALR, &Capstone2LlvmIrTranslatorRiscv_impl::translateJalr},
		{RISCV_INS_LB, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_LBU, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_LD, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_LH, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_LHU, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_LR_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateLr},
		{RISCV_INS_LR_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateLr},
		{RISCV_INS_LR_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateLr},
		{RISCV_INS_LR_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateLr},
		{RISCV_INS_LR_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateLr},
		{RISCV_INS_LR_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateLr},
		{RISCV_INS_LR_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateLr},
		{RISCV_INS_LR_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateLr},
		{RISCV_INS_LUI, &Capstone2LlvmIrTranslatorRiscv_impl::translateLui},
		{RISCV_INS_LW, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_LWU, &Capstone2LlvmIrTranslatorRiscv_impl::translateLoad},
		{RISCV_INS_MAX, &Capstone2LlvmIrTranslatorRiscv_impl::translateMinMax},
		{RISCV_INS_MAXU, &Capstone2LlvmIrTranslatorRiscv_impl::translateMinMax},
		{RISCV_INS_MIN, &Capstone2LlvmIrTranslatorRiscv_impl::translateMinMax},
		{RISCV_INS_MINU, &Capstone2LlvmIrTranslatorRiscv_impl::translateMinMax},
		{RISCV_INS_MRET, nullptr},
		{RISCV_INS_MUL, &Capstone2LlvmIrTranslatorRiscv_impl::translateMul},
		{RISCV_INS_MULH, &Capstone2LlvmIrTranslatorRiscv_impl::translateMul},
		{RISCV_INS_MULHSU, &Capstone2LlvmIrTranslatorRiscv_impl::translateMul},
		{RISCV_INS_MULHU, &Capstone2LlvmIrTranslatorRiscv_impl::translateMul},
		{RISCV_INS_MULW, &Capstone2LlvmIrTranslatorRiscv_impl::translateMul},
		{RISCV_INS_OR, &Capstone2LlvmIrTranslatorRiscv_impl::translateOr},
		{RISCV_INS_ORC_B, &Capstone2LlvmIrTranslatorRiscv_impl::translateOrcB},
		{RISCV_INS_ORI, &Capstone2LlvmIrTranslatorRiscv_impl::translateOr},
		{RISCV_INS_ORN, &Capstone2LlvmIrTranslatorRiscv_impl::translateAndn},
		{RISCV_INS_PACK, &Capstone2LlvmIrTranslatorRiscv_impl::translatePack},
		{RISCV_INS_PACKH, &Capstone2LlvmIrTranslatorRiscv_impl::translatePack},
		{RISCV_INS_PACKW, &Capstone2LlvmIrTranslatorRiscv_impl::translatePack},
		{RISCV_INS_REM, &Capstone2LlvmIrTranslatorRiscv_impl::translateDiv},
		{RISCV_INS_REMU, &Capstone2LlvmIrTranslatorRiscv_impl::translateDiv},
		{RISCV_INS_REMUW, &Capstone2LlvmIrTranslatorRiscv_impl::translateDiv},
		{RISCV_INS_REMW, &Capstone2LlvmIrTranslatorRiscv_impl::translateDiv},
		{RISCV_INS_REV8, &Capstone2LlvmIrTranslatorRiscv_impl::translateRev8},
		{RISCV_INS_ROL, &Capstone2LlvmIrTranslatorRiscv_impl::translateRotate},
		{RISCV_INS_ROLW, &Capstone2LlvmIrTranslatorRiscv_impl::translateRotate},
		{RISCV_INS_ROR, &Capstone2LlvmIrTranslatorRiscv_impl::translateRotate},
		{RISCV_INS_RORI, &Capstone2LlvmIrTranslatorRiscv_impl::translateRotate},
		{RISCV_INS_RORIW, &Capstone2LlvmIrTranslatorRiscv_impl::translateRotate},
		{RISCV_INS_RORW, &Capstone2LlvmIrTranslatorRiscv_impl::translateRotate},
		{RISCV_INS_SB, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_SC_D, &Capstone2LlvmIrTranslatorRiscv_impl::translateSc},
		{RISCV_INS_SC_D_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateSc},
		{RISCV_INS_SC_D_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateSc},
		{RISCV_INS_SC_D_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateSc},
		{RISCV_INS_SC_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateSc},
		{RISCV_INS_SC_W_AQ, &Capstone2LlvmIrTranslatorRiscv_impl::translateSc},
		{RISCV_INS_SC_W_AQ_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateSc},
		{RISCV_INS_SC_W_RL, &Capstone2LlvmIrTranslatorRiscv_impl::translateSc},
		{RISCV_INS_SD, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_SEXT_B, &Capstone2LlvmIrTranslatorRiscv_impl::translateSextZext},
		{RISCV_INS_SEXT_H, &Capstone2LlvmIrTranslatorRiscv_impl::translateSextZext},
		{RISCV_INS_SFENCE_VMA, nullptr},
		{RISCV_INS_SH, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_SH1ADD, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
		{RISCV_INS_SH1ADD_UW, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
		{RISCV_INS_SH2ADD, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
		{RISCV_INS_SH2ADD_UW, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
		{RISCV_INS_SH3ADD, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
		{RISCV_INS_SH3ADD_UW, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
		{RISCV_INS_SLL, &Capstone2LlvmIrTranslatorRiscv_impl::translateSll},
		{RISCV_INS_SLLI, &Capstone2LlvmIrTranslatorRiscv_impl::translateSll},
		{RISCV_INS_SLLI_UW, &Capstone2LlvmIrTranslatorRiscv_impl::translateSlliUw},
		{RISCV_INS_SLLIW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_SLLW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_SLT, &Capstone2LlvmIrTranslatorRiscv_impl::translateSlt},
		{RISCV_INS_SLTI, &Capstone2LlvmIrTranslatorRiscv_impl::translateSlt},
		{RISCV_INS_SLTIU, &Capstone2LlvmIrTranslatorRiscv_impl::translateSltu},
		{RISCV_INS_SLTU, &Capstone2LlvmIrTranslatorRiscv_impl::translateSltu},
		{RISCV_INS_SRA, &Capstone2LlvmIrTranslatorRiscv_impl::translateSra},
		{RISCV_INS_SRAI, &Capstone2LlvmIrTranslatorRiscv_impl::translateSra},
		{RISCV_INS_SRAIW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_SRAW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_SRET, nullptr},
		{RISCV_INS_SRL, &Capstone2LlvmIrTranslatorRiscv_impl::translateSrl},
		{RISCV_INS_SRLI, &Capstone2LlvmIrTranslatorRiscv_impl::translateSrl},
		{RISCV_INS_SRLIW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_SRLW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_SUB, &Capstone2LlvmIrTranslatorRiscv_impl::translateSub},
		{RISCV_INS_SUBW, &Capstone2LlvmIrTranslatorRiscv_impl::translateOp32},
		{RISCV_INS_SW, &Capstone2LlvmIrTranslatorRiscv_impl::translateStore},
		{RISCV_INS_UNIMP, &Capstone2LlvmIrTranslatorRiscv_impl::translateNop},
		{RISCV_INS_WFI, nullptr},
		{RISCV_INS_XOR, &Capstone2LlvmIrTranslatorRiscv_impl::translateXor},
		{RISCV_INS_XORI, &Capstone2LlvmIrTranslatorRiscv_impl::translateXor},
		{RISCV_INS_XNOR, &Capstone2LlvmIrTranslatorRiscv_impl::translateAndn},
		{RISCV_INS_ZEXT_H, &Capstone2LlvmIrTranslatorRiscv_impl::translateSextZext},
		{RISCV_INS_ZEXT_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},

		{RISCV_INS_ALIAS_NOP, &Capstone2LlvmIrTranslatorRiscv_impl::translateNop},
		{RISCV_INS_ALIAS_J, &Capstone2LlvmIrTranslatorRiscv_impl::translateJal},
		{RISCV_INS_ALIAS_JAL, &Capstone2LlvmIrTranslatorRiscv_impl::translateJal},
		{RISCV_INS_ALIAS_JR, &Capstone2LlvmIrTranslatorRiscv_impl::translateJalr},
		{RISCV_INS_ALIAS_JALR, &Capstone2LlvmIrTranslatorRiscv_impl::translateJalr},
		{RISCV_INS_ALIAS_RET, &Capstone2LlvmIrTranslatorRiscv_impl::translateJalr},
		{RISCV_INS_ALIAS_BEQZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_ALIAS_BNEZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_ALIAS_BLEZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_ALIAS_BGEZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_ALIAS_BLTZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_ALIAS_BGTZ, &Capstone2LlvmIrTranslatorRiscv_impl::translateBranch},
		{RISCV_INS_ALIAS_CSRR, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_CSRW, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_CSRS, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_CSRC, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_CSRWI, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_CSRSI, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_CSRCI, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_FRFLAGS, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_FSFLAGS, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_FRRM, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_FSRM, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_FRCSR, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_FSCSR, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_RDCYCLE, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_RDTIME, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_RDINSTRET, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_RDCYCLEH, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_RDTIMEH, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_RDINSTRETH, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_FSFLAGSI, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_FSRMI, &Capstone2LlvmIrTranslatorRiscv_impl::translateCsr},
		{RISCV_INS_ALIAS_ZEXT_W, &Capstone2LlvmIrTranslatorRiscv_impl::translateShadd},
};

} // namespace capstone2llvmir
} // namespace retdec
