/**
 * @file include/retdec/csharp_emitter/cs_file_emitter.h
 * @brief Top-level C# source file generator.
 *
 * ## Output layout
 *
 * One `.cs` file per top-level type (matching Visual Studio conventions):
 *
 * ```
 * // <auto-generated by retdec>
 * // Original assembly: MyLib.dll  CLR 4.0
 *
 * #nullable enable
 *
 * using System;
 * using System.Collections.Generic;
 * ...
 *
 * namespace MyLib;          // C# 10 file-scoped namespace (or classic block)
 *
 * public class Foo
 * {
 *     ...
 * }
 * ```
 *
 * ## Using directive computation
 *
 * We collect all namespaces referenced by the type body, de-duplicate, sort,
 * and emit them.  The following groups are separated by blank lines:
 *
 *   1. System.* namespaces
 *   2. Microsoft.* namespaces
 *   3. Third-party (everything else)
 *   4. Project-internal namespaces (same root as the assembly)
 *
 * ## Multi-file output
 *
 * `CsFileEmitter::emitModule()` returns a map from filename to source string.
 * The caller is responsible for writing them to disk.
 *
 * ## Top-level statements (C# 9+)
 *
 * If the assembly has a `<Module>` class with a `Main` method and csharpVersion >= 9,
 * we emit it as top-level statements in `Program.cs`.
 */

#ifndef RETDEC_CSHARP_EMITTER_CS_FILE_EMITTER_H
#define RETDEC_CSHARP_EMITTER_CS_FILE_EMITTER_H

#include "retdec/bc_module/bc_module.h"
#include "retdec/cil_reconstruct/cil_reconstructor.h"
#include "retdec/csharp_emitter/cs_type_emitter.h"
#include "retdec/csharp_emitter/cs_writer.h"

#include <string>
#include <unordered_map>
#include <vector>

namespace retdec {
namespace csharp_emitter {

using namespace bc_module;
using namespace cil_reconstruct;

// ─── CsEmitOptions ───────────────────────────────────────────────────────────

struct CsEmitOptions {
    int  csharpVersion    = 12;      ///< Target language version

    // File layout
    bool fileScopedNamespace  = true;   ///< C# 10+ file-scoped namespace
    bool nullableEnable       = true;   ///< Emit #nullable enable
    bool emitAutoGenHeader    = true;   ///< Emit // <auto-generated> header
    bool emitAssemblyInfo     = true;   ///< Emit assembly name / CLR version in header

    // Using directives
    bool sortUsings           = true;
    bool groupUsings          = true;   ///< Blank line between System/MS/third-party
    bool omitRedundantUsings  = true;   ///< Skip usings not needed in that file

    // Member emission
    bool omitCompilerGenerated= true;   ///< Skip SM helper classes
    bool emitXmlDoc           = true;
    bool preferAutoProperties = true;
    bool emitRegions          = false;

    // Modern syntax
    bool useVarKeyword        = true;
    bool preferStringInterp   = true;
    bool emitExpressionBodies = true;

    // Output
    std::string outputEncoding = "utf-8";
};

// ─── CsFileEmitResult ────────────────────────────────────────────────────────

struct CsFileEmitResult {
    /// Map from relative path (e.g. "MyLib/Foo.cs") to source text.
    std::unordered_map<std::string, std::string> files;

    int  totalClasses   = 0;
    int  totalMethods   = 0;
    int  emittedClasses = 0;
    int  emittedMethods = 0;
    int  skippedClasses = 0;  ///< Compiler-generated, skipped

    std::vector<std::string> warnings;
    std::vector<std::string> errors;
};

// ─── CsFileEmitter ───────────────────────────────────────────────────────────

/**
 * @brief Orchestrates emission of an entire BcModule as a set of .cs files.
 */
class CsFileEmitter {
public:
    explicit CsFileEmitter(CsEmitOptions opts = CsEmitOptions{});

    /**
     * @brief Emit all classes in the module.
     *
     * @param module   The parsed .NET assembly (BcModule).
     * @param results  Per-method reconstruction results from CilReconstructor.
     * @return         Map from filename to source text + statistics.
     */
    CsFileEmitResult emitModule(
        const BcModule& module,
        const std::unordered_map<std::string, CilReconstructResult>& results) const;

    /**
     * @brief Emit a single class to a string.
     */
    std::string emitClass(
        const BcClass& cls,
        const BcModule& module,
        const std::unordered_map<std::string, CilReconstructResult>& results) const;

private:
    CsEmitOptions opts_;

    // ── File generation ───────────────────────────────────────────────────────

    std::string makeFileName(const BcClass& cls) const;
    std::string makeHeader(const BcModule& module) const;
    std::string makeNullableDirective() const;

    // ── Using computation ─────────────────────────────────────────────────────

    std::vector<std::string> computeUsings(
        const BcClass& cls,
        const BcModule& module,
        const std::unordered_map<std::string, CilReconstructResult>& results) const;

    void collectNamespaces(
        const BcClass& cls,
        const std::unordered_map<std::string, CilReconstructResult>& results,
        std::vector<std::string>& namespaces) const;

    std::string emitUsingDirectives(
        const std::vector<std::string>& usings,
        const std::string& ownNamespace) const;

    // ── Namespace emission ────────────────────────────────────────────────────

    void emitNamespaceHeader(CsWriter& w, const std::string& ns) const;
    void emitNamespaceFooter(CsWriter& w, const std::string& ns) const;

    // ── Top-level statements ─────────────────────────────────────────────────

    bool hasTopLevelStatements(const BcModule& module) const;
    std::string emitTopLevelStatements(
        const BcModule& module,
        const std::unordered_map<std::string, CilReconstructResult>& results) const;

    // ── Helpers ───────────────────────────────────────────────────────────────

    bool shouldSkip(const BcClass& cls) const;
    std::string namespaceOf(const BcClass& cls) const;
    CsWriter::Options makeWriterOptions() const;
};

} // namespace csharp_emitter
} // namespace retdec

#endif // RETDEC_CSHARP_EMITTER_CS_FILE_EMITTER_H
