/**
 * @file tests/verification/text_transcode_proof.cpp
 * @brief ESBMC proofs for include/retdec/utils/text_transcode.h.
 * @copyright (c) 2026 Odin Loch trading as Imortek
 *
 * Two families of property live here, and they are proved differently.
 *
 * The sizing lemmas -- hexCapacity, bitsCapacity, the index arithmetic, the
 * UTF-8 encoder -- have no loops, so their inputs stay fully symbolic over the
 * whole 64-bit (or, for a code point, 32-bit) domain and the result is a proof
 * rather than a bounded search. These are the ones that matter for the bug:
 * a product that wraps is a property of the arithmetic, not of any particular
 * buffer.
 *
 * The whole-function properties run the real loops over exactly-sized symbolic
 * buffers. Exactly-sized is the point: every input array is `n` long and every
 * output array is exactly the capacity the kernel was told it had, so ESBMC's
 * array-bounds checking (on by default) fails the run if any input at all could
 * drive an index off either end. That is how property 1 of the spec -- reads
 * only within [0, n), writes only within [0, outCap), including the in[i+1]
 * lookahead in both scanners -- is discharged: not by an assertion, but by the
 * absence of a reachable one.
 *
 * Unwinding assertions are generated by default, so --unwind is a real bound
 * and a loop that could run further fails loudly.
 */

// ESBMC-OPTIONS: --unwind 18
// ESBMC-SOLVER: --boolector
//
// 18, because the longest loop in this file is a checking loop over a 16-byte
// output buffer (bytesToBits of two bytes) and the unwinding assertion needs
// one iteration past its trip count. This was measured rather than guessed:
// at --unwind 14 ESBMC failed proof_bytes_to_bits_refuses_a_short_buffer with
// "unwinding assertion loop 6" -- the bound is real, and a loop that could run
// further is reported rather than silently truncated.
//
// Boolector, and the difference is not marginal. All 32 proofs below discharge
// under boolector in 40s together, the slowest one in 5s. Under z3, with a 400s
// budget per proof, proof_hex_capacity_is_exact_or_zero and
// proof_hex_round_trips both time out -- the first is a symbolic 64-bit
// capacity against a symbolic 64-bit division, which is the shape z3 is worst
// at here.
//
// The spurious "arithmetic overflow on div" that pins bounds_proof.cpp to z3
// does not arise here, even though this header calls bounds::mulFits, which
// divides. That check is discharged as SAT only when the numerator can be
// INT64_MIN and the divisor -1. Every division reachable from this header has a
// literal numerator -- SIZE_MAX inside mulFits, UINT64_MAX in kMaxU64Div10 --
// so no such assignment exists, and boolector agrees: every div check in every
// proof below passes. Measured, not assumed.

#include "retdec/utils/text_transcode.h"

#include <cassert>
#include <cstddef>
#include <cstdint>

using namespace retdec::utils::txt;

extern "C" {
std::uint8_t  nondet_u8();
std::uint32_t nondet_u32();
std::uint64_t nondet_u64();
char          nondet_char();
bool          nondet_bool();
std::size_t   nondet_size();
}

#ifdef RETDEC_VERIFY_SYNTAX_ONLY
#define __ESBMC_assume(cond) ((void) sizeof((cond) ? 1 : 0))
#endif

namespace {

/// Four bytes is enough to make every hex path distinct: a first byte with no
/// separator before it, three with one, and an even count so the round trip
/// through hexToBytes has something to fail on. It keeps the loops inside the
/// unwind bound.
constexpr std::size_t kBytes = 4;

/// hexCapacity(4, false) and hexCapacity(4, true). Written out rather than
/// called so the arrays below are exactly the size the kernel is told they are;
/// proof_hex_capacity_is_exact_or_zero proves the two agree.
constexpr std::size_t kHexPlain  = 8;   // 2 * 4
constexpr std::size_t kHexSpaced = 11;  // 3 * 4 - 1

/// Three UTF-16 units: a surrogate pair plus one more unit, which is the
/// shortest input that exercises a pair, a lone surrogate and a trailing unit
/// the lookahead must not run past.
constexpr std::size_t kUnits = 3;
constexpr std::size_t kUtf16Bytes = kUnits * 2;
constexpr std::size_t kUtf8Cap = kUnits * 3;

unsigned byteAt(const char* p, std::size_t i)
{
	return static_cast<unsigned>(static_cast<unsigned char>(p[i]));
}

} // namespace

// ─── sizing, over the whole domain ───────────────────────────────────────────

/// Spec property 2, and the counterexample to conversion.h:59.
extern "C" void proof_hex_capacity_is_exact_or_zero()
{
	const std::size_t n = nondet_size();
	const bool spaced = nondet_bool();
	const std::size_t perByte = spaced ? kSpacedHexCharsPerByte : kHexCharsPerByte;

	const std::size_t cap = hexCapacity(n, spaced);

	// Zero exactly when there is nothing to render or the product does not fit.
	// The spec states the second half alone; n == 0 is the boundary it misses,
	// because `3 * 0 - 1` is not a length and zero bytes need zero characters.
	assert((cap == 0) == (n == 0 || !retdec::utils::bounds::mulFits(perByte, n)));

	if (cap != 0)
	{
		// Exact, and stated by division so the harness does not itself form the
		// product it is proving representable.
		assert(cap / perByte == (spaced ? n - 1 : n));
		assert(spaced ? (cap % perByte == perByte - 1) : (cap % perByte == 0));
		// And the product really does fit, which is what the caller resizes by.
		assert(cap <= SIZE_MAX - 1);
	}
}

/// Spec property 4, second half: the index arithmetic is total for every length
/// a std::string can have, which conversion.cpp:171's `unsigned int` counter is
/// not.
extern "C" void proof_hex_index_arithmetic_is_total()
{
	const std::size_t n = nondet_size();
	const std::size_t i = nondet_size();
	__ESBMC_assume(i < (n >> 1));

	// The two indices hexToBytes forms for pair i. Neither can wrap and both
	// stay inside the run, for every n up to SIZE_MAX.
	const std::size_t at = i * kHexCharsPerByte;
	assert(at >= i);            // no wrap in the doubling
	assert(at + 1 > at);        // no wrap in the lookahead
	assert(at + 1 < n);         // both inside the input
}

extern "C" void proof_bits_capacity_is_exact_or_zero()
{
	const std::size_t n = nondet_size();
	const std::size_t cap = bitsCapacity(n);

	assert((cap == 0) == (n == 0 || !retdec::utils::bounds::mulFits(kBitsPerByte, n)));
	if (cap != 0) assert(cap / kBitsPerByte == n && cap % kBitsPerByte == 0);
}

extern "C" void proof_utf16_and_mutf8_capacities_are_exact_or_zero()
{
	const std::size_t units = nondet_size();

	const std::size_t a = utf8CapacityForUtf16(units);
	assert((a == 0) == (units == 0
		|| !retdec::utils::bounds::mulFits(kUtf8BytesPerUtf16Unit, units)));
	if (a != 0) assert(a / kUtf8BytesPerUtf16Unit == units);

	const std::size_t b = utf8CapacityForMutf8(units);
	assert((b == 0) == (units == 0
		|| !retdec::utils::bounds::mulFits(kUtf8BytesPerMutf8Unit, units)));
	if (b != 0) assert(b / kUtf8BytesPerMutf8Unit == units);
}

// ─── the hex tables, as data ─────────────────────────────────────────────────

/// Spec property 3. The 512-character table is 512 chances to mistype a digit,
/// and this is the only thing that would catch one: every byte, both cases,
/// checked against digits computed rather than looked up.
extern "C" void proof_byte_to_hex_matches_the_arithmetic()
{
	const std::uint8_t b = nondet_u8();
	const bool upper = nondet_bool();

	char hi = 0, lo = 0;
	byteToHex(b, upper, hi, lo);

	assert(hi == hexDigit(static_cast<unsigned>(b) >> 4, upper));
	assert(lo == hexDigit(static_cast<unsigned>(b) & 0xFu, upper));
	// Both tables are NUL-terminated where the caller's index arithmetic
	// assumes, so a byte of 0xFF cannot read the terminator as a digit.
	assert(hi != '\0' && lo != '\0');
}

/// hexValue inverts hexDigit, and refuses everything else -- which strtol at
/// conversion.cpp:174 does not: it returns 0 for "zz".
extern "C" void proof_hex_value_inverts_hex_digit()
{
	const char c = nondet_char();
	const int v = hexValue(c);

	assert(v >= -1 && v <= 15);
	if (v >= 0)
		assert(c == hexDigit(static_cast<unsigned>(v), true)
			|| c == hexDigit(static_cast<unsigned>(v), false));

	const unsigned d = nondet_u32() & 0xFu;
	assert(hexValue(hexDigit(d, true)) == static_cast<int>(d));
	assert(hexValue(hexDigit(d, false)) == static_cast<int>(d));
}

// ─── bytesToHex ──────────────────────────────────────────────────────────────

/// Spec property 2, second half, and property 3 over a whole run: the plain
/// form writes exactly 2n characters into a buffer of exactly 2n, and every
/// pair is the byte it came from.
extern "C" void proof_bytes_to_hex_plain_renders_every_byte()
{
	std::uint8_t in[kBytes];
	for (std::size_t i = 0; i < kBytes; ++i) in[i] = nondet_u8();
	char out[kHexPlain];
	const bool upper = nondet_bool();

	const std::size_t w = bytesToHex(in, kBytes, out, kHexPlain, upper, false);
	assert(w == hexCapacity(kBytes, false));

	for (std::size_t i = 0; i < kBytes; ++i)
	{
		char hi = 0, lo = 0;
		byteToHex(in[i], upper, hi, lo);
		assert(out[i * 2] == hi);
		assert(out[i * 2 + 1] == lo);
	}
}

extern "C" void proof_bytes_to_hex_spaced_renders_every_byte()
{
	std::uint8_t in[kBytes];
	for (std::size_t i = 0; i < kBytes; ++i) in[i] = nondet_u8();
	char out[kHexSpaced];
	const bool upper = nondet_bool();

	const std::size_t w = bytesToHex(in, kBytes, out, kHexSpaced, upper, true);
	assert(w == hexCapacity(kBytes, true));

	for (std::size_t i = 0; i < kBytes; ++i)
	{
		// Byte i starts at 3i, one past the separator that precedes it.
		const std::size_t at = i * 3;
		if (i > 0) assert(out[at - 1] == ' ');
		char hi = 0, lo = 0;
		byteToHex(in[i], upper, hi, lo);
		assert(out[at] == hi);
		assert(out[at + 1] == lo);
	}
}

/// The refusal itself. conversion.h:59 has no equivalent: it resizes to the
/// wrapped product and writes 2*size characters regardless.
extern "C" void proof_bytes_to_hex_refuses_a_short_buffer()
{
	std::uint8_t in[kBytes];
	for (std::size_t i = 0; i < kBytes; ++i) in[i] = nondet_u8();
	char out[kHexSpaced];
	const std::size_t n = nondet_size();
	__ESBMC_assume(n <= kBytes);
	const std::size_t outCap = nondet_size();
	__ESBMC_assume(outCap <= kHexSpaced);
	const bool spaced = nondet_bool();

	// Guard the whole buffer so a write anywhere is visible, not just one past
	// the end.
	for (std::size_t i = 0; i < kHexSpaced; ++i) out[i] = '#';

	const std::size_t w = bytesToHex(in, n, out, outCap, nondet_bool(), spaced);
	const std::size_t need = hexCapacity(n, spaced);

	if (need == 0 || outCap < need)
	{
		assert(w == 0);
		// Nothing was written at all, which is what makes the refusal safe for
		// a caller that sized its buffer from a wrapped product.
		for (std::size_t i = 0; i < kHexSpaced; ++i) assert(out[i] == '#');
	}
	else
	{
		assert(w == need);
		assert(w <= outCap);
		// Never past what it was told it had.
		for (std::size_t i = need; i < kHexSpaced; ++i) assert(out[i] == '#');
	}
}

/// A null input is a refusal, not a dereference: conversion.h checks `data ==
/// nullptr` but gpu_scanner_cpu.cpp:32 does not.
extern "C" void proof_bytes_to_hex_tolerates_null()
{
	char out[kHexPlain];
	assert(bytesToHex(nullptr, nondet_size(), out, kHexPlain, true, false) == 0);
	std::uint8_t in[kBytes];
	for (std::size_t i = 0; i < kBytes; ++i) in[i] = nondet_u8();
	assert(bytesToHex(in, kBytes, nullptr, nondet_size(), true, false) == 0);
}

// ─── hexToBytes ──────────────────────────────────────────────────────────────

/// Spec property 4. Note what is NOT assumed: the characters are fully
/// symbolic, so the accept/reject decision is proved for every string.
extern "C" void proof_hex_to_bytes_accepts_exactly_the_hex_runs()
{
	char in[kHexPlain];
	for (std::size_t i = 0; i < kHexPlain; ++i) in[i] = nondet_char();
	std::uint8_t out[kBytes];
	for (std::size_t i = 0; i < kBytes; ++i) out[i] = 0xAA;

	const std::size_t n = nondet_size();
	__ESBMC_assume(n <= kHexPlain);

	std::size_t written = SIZE_MAX;
	const bool ok = hexToBytes(in, n, out, kBytes, written);

	// Every character in the accepted run really was a hex digit. strtol
	// returns 0 for a non-digit and reports nothing, so a corrupt dump becomes
	// a run of NULs that the caller believes it parsed.
	bool allHex = true;
	for (std::size_t i = 0; i < n; ++i)
		if (hexValue(in[i]) < 0) allHex = false;

	assert(ok == ((n & 1u) == 0 && allHex));

	if (ok)
	{
		// Exactly n/2 bytes, so an odd trailing nibble was never promoted.
		assert(written == (n >> 1));
		for (std::size_t i = 0; i < kBytes; ++i)
			if (i < written)
				assert(out[i] == static_cast<std::uint8_t>(
					(hexValue(in[i * 2]) << 4) | hexValue(in[i * 2 + 1])));
			else
				assert(out[i] == 0xAA);   // untouched past what it wrote
	}
	else
	{
		assert(written == 0);
	}
}

/// The odd length, stated on its own because it is the case conversion.cpp:171
/// gets wrong quietly: "abc" there parses as ab 0c -- a byte whose value came
/// from a nibble that was never there.
extern "C" void proof_hex_to_bytes_refuses_an_odd_length()
{
	char in[kHexPlain];
	for (std::size_t i = 0; i < kHexPlain; ++i) in[i] = nondet_char();
	std::uint8_t out[kBytes];
	const std::size_t n = nondet_size();
	__ESBMC_assume(n <= kHexPlain);
	__ESBMC_assume((n & 1u) != 0);

	std::size_t written = SIZE_MAX;
	assert(!hexToBytes(in, n, out, kBytes, written));
	assert(written == 0);
}

/// Round trip: rendering and re-parsing is the identity on the bytes.
extern "C" void proof_hex_round_trips()
{
	std::uint8_t in[kBytes];
	for (std::size_t i = 0; i < kBytes; ++i) in[i] = nondet_u8();
	char mid[kHexPlain];
	std::uint8_t back[kBytes];

	const bool upper = nondet_bool();
	const std::size_t w = bytesToHex(in, kBytes, mid, kHexPlain, upper, false);
	assert(w == kHexPlain);

	std::size_t written = 0;
	assert(hexToBytes(mid, w, back, kBytes, written));
	assert(written == kBytes);
	for (std::size_t i = 0; i < kBytes; ++i) assert(back[i] == in[i]);
}

// ─── bytesToBits ─────────────────────────────────────────────────────────────

/// Spec property 5. The shift checks are ESBMC's (--ub-shift-check): if any
/// operand could be negative or any count reach the width, the run fails.
extern "C" void proof_bytes_to_bits_writes_eight_per_byte()
{
	constexpr std::size_t kN = 2;
	std::uint8_t in[kN];
	for (std::size_t i = 0; i < kN; ++i) in[i] = nondet_u8();
	char out[kN * 8];

	const std::size_t w = bytesToBits(in, kN, out, kN * 8);
	assert(w == kN * 8);

	for (std::size_t i = 0; i < kN; ++i)
		for (std::size_t j = 0; j < 8; ++j)
		{
			const unsigned expect = (static_cast<unsigned>(in[i]) >> (7 - j)) & 1u;
			assert(out[i * 8 + j] == (expect ? '1' : '0'));
		}
}

/// The int8_t instantiation, which is the one that is undefined today.
/// conversion.h:204 computes `(item << j) & 0x80`; for any element from 0x80 up
/// `item` promotes to a negative int and the left shift is undefined behaviour.
/// The overload here reinterprets instead, so the two agree bit for bit and
/// neither shifts a negative value.
extern "C" void proof_bytes_to_bits_agrees_for_signed_and_unsigned()
{
	constexpr std::size_t kN = 2;
	std::int8_t sin[kN];
	std::uint8_t uin[kN];
	for (std::size_t i = 0; i < kN; ++i)
	{
		const std::uint8_t b = nondet_u8();
		uin[i] = b;
		sin[i] = static_cast<std::int8_t>(b);
	}
	char a[kN * 8];
	char b[kN * 8];

	assert(bytesToBits(sin, kN, a, kN * 8) == bytesToBits(uin, kN, b, kN * 8));
	for (std::size_t i = 0; i < kN * 8; ++i) assert(a[i] == b[i]);
}

extern "C" void proof_bytes_to_bits_refuses_a_short_buffer()
{
	constexpr std::size_t kN = 2;
	std::uint8_t in[kN];
	for (std::size_t i = 0; i < kN; ++i) in[i] = nondet_u8();
	char out[kN * 8];
	for (std::size_t i = 0; i < kN * 8; ++i) out[i] = '#';

	const std::size_t outCap = nondet_size();
	__ESBMC_assume(outCap < kN * 8);

	assert(bytesToBits(in, kN, out, outCap) == 0);
	for (std::size_t i = 0; i < kN * 8; ++i) assert(out[i] == '#');
}

// ─── the UTF-8 encoder, over every code point ────────────────────────────────

/// Spec property 6, the half that does not need a scanner: for EVERY 32-bit
/// value, the encoder writes a well-formed UTF-8 sequence that decodes back to
/// the scalar value it was given, with a surrogate or an out-of-range value
/// replaced rather than encoded. Loop-free, so this is a proof over the whole
/// 32-bit domain and not a bounded search.
extern "C" void proof_encode_utf8_is_well_formed()
{
	const std::uint32_t raw = nondet_u32();
	char out[4] = {0, 0, 0, 0};

	const std::size_t len = encodeUtf8(raw, out);
	assert(len == utf8Length(raw));
	assert(len >= 1 && len <= 4);

	// What the encoder is obliged to have produced.
	const std::uint32_t want =
		(raw > kMaxCodePoint || (raw >= kHighSurrogateFirst && raw <= kLowSurrogateLast))
			? kReplacement : raw;

	std::uint32_t got = 0;
	if (len == 1)
	{
		assert(byteAt(out, 0) < 0x80);
		got = byteAt(out, 0);
	}
	else if (len == 2)
	{
		assert((byteAt(out, 0) & 0xE0u) == 0xC0u);
		assert((byteAt(out, 1) & 0xC0u) == 0x80u);
		got = ((byteAt(out, 0) & 0x1Fu) << 6) | (byteAt(out, 1) & 0x3Fu);
		assert(got >= 0x80);           // not overlong
	}
	else if (len == 3)
	{
		assert((byteAt(out, 0) & 0xF0u) == 0xE0u);
		assert((byteAt(out, 1) & 0xC0u) == 0x80u);
		assert((byteAt(out, 2) & 0xC0u) == 0x80u);
		got = ((byteAt(out, 0) & 0x0Fu) << 12)
			| ((byteAt(out, 1) & 0x3Fu) << 6) | (byteAt(out, 2) & 0x3Fu);
		assert(got >= 0x800);          // not overlong
	}
	else
	{
		assert((byteAt(out, 0) & 0xF8u) == 0xF0u);
		assert((byteAt(out, 1) & 0xC0u) == 0x80u);
		assert((byteAt(out, 2) & 0xC0u) == 0x80u);
		assert((byteAt(out, 3) & 0xC0u) == 0x80u);
		got = ((byteAt(out, 0) & 0x07u) << 18) | ((byteAt(out, 1) & 0x3Fu) << 12)
			| ((byteAt(out, 2) & 0x3Fu) << 6) | (byteAt(out, 3) & 0x3Fu);
		assert(got >= kSupplementaryBase);
	}

	assert(got == want);
	// The property both .NET decoders violate: no output ever denotes a
	// surrogate. Theirs emit ED A0 80 .. ED BF BF for one directly.
	assert(!(got >= kHighSurrogateFirst && got <= kLowSurrogateLast));
	assert(got <= kMaxCodePoint);
}

// ─── utf16leToUtf8 ───────────────────────────────────────────────────────────

/// Spec property 6: writes at most utf8CapacityForUtf16(inBytes / 2) bytes, and
/// never outside the buffer it was given. The input is three fully symbolic
/// units, so the surrogate lookahead is exercised at every position including
/// the last, where `i + 1 < units` is the only thing keeping in[at + 3] inside
/// the array.
extern "C" void proof_utf16_stays_inside_both_buffers()
{
	std::uint8_t in[kUtf16Bytes];
	for (std::size_t i = 0; i < kUtf16Bytes; ++i) in[i] = nondet_u8();
	char out[kUtf8Cap];

	const std::size_t w = utf16leToUtf8(in, kUtf16Bytes, out, kUtf8Cap);
	assert(w <= utf8CapacityForUtf16(kUnits));
	assert(w <= kUtf8Cap);
	// At least one byte per unit, so nothing was silently dropped.
	assert(w >= kUnits);
}

/// A trailing odd byte is dropped, not read: the odd-length call produces
/// exactly what the even-length call does. Stated this way rather than left to
/// the bounds check because "not read" and "read and ignored" are different
/// facts, and only the first is safe at the end of a mapping.
extern "C" void proof_utf16_drops_a_trailing_odd_byte()
{
	std::uint8_t in[kUtf16Bytes + 1];
	for (std::size_t i = 0; i < kUtf16Bytes + 1; ++i) in[i] = nondet_u8();
	char a[kUtf8Cap];
	char b[kUtf8Cap];

	const std::size_t wa = utf16leToUtf8(in, kUtf16Bytes + 1, a, kUtf8Cap);
	const std::size_t wb = utf16leToUtf8(in, kUtf16Bytes, b, kUtf8Cap);

	assert(wa == wb);
	for (std::size_t i = 0; i < kUtf8Cap; ++i)
		if (i < wa) assert(a[i] == b[i]);
}

/// A well-formed pair becomes one four-byte sequence, which is the character
/// the pair exists to denote. Both .NET decoders emit two three-byte surrogate
/// sequences here instead.
extern "C" void proof_utf16_combines_a_surrogate_pair()
{
	const std::uint32_t hi = nondet_u32();
	const std::uint32_t lo = nondet_u32();
	__ESBMC_assume(hi >= kHighSurrogateFirst && hi <= kHighSurrogateLast);
	__ESBMC_assume(lo >= kLowSurrogateFirst && lo <= kLowSurrogateLast);

	std::uint8_t in[4] = {
		static_cast<std::uint8_t>(hi & 0xFFu), static_cast<std::uint8_t>(hi >> 8),
		static_cast<std::uint8_t>(lo & 0xFFu), static_cast<std::uint8_t>(lo >> 8)
	};
	char out[6];

	const std::size_t w = utf16leToUtf8(in, 4, out, 6);
	assert(w == 4);

	char want[4];
	assert(encodeUtf8(combineSurrogates(hi, lo), want) == 4);
	for (std::size_t i = 0; i < 4; ++i) assert(out[i] == want[i]);

	// And the combined value really is a supplementary scalar value.
	const std::uint32_t cp = combineSurrogates(hi, lo);
	assert(cp >= kSupplementaryBase && cp <= kMaxCodePoint);
}

/// A lone surrogate -- high with nothing after it, high followed by a
/// non-surrogate, or a bare low -- becomes U+FFFD, EF BF BD.
extern "C" void proof_utf16_lone_surrogate_becomes_replacement()
{
	const std::uint32_t u = nondet_u32();
	__ESBMC_assume(u >= kHighSurrogateFirst && u <= kLowSurrogateLast);

	std::uint8_t in[2] = {
		static_cast<std::uint8_t>(u & 0xFFu), static_cast<std::uint8_t>(u >> 8)
	};
	char out[3];

	assert(utf16leToUtf8(in, 2, out, 3) == 3);
	assert(byteAt(out, 0) == 0xEF);
	assert(byteAt(out, 1) == 0xBF);
	assert(byteAt(out, 2) == 0xBD);
}

/// The structural form of the same thing over a whole symbolic buffer: no
/// three-byte sequence in the output denotes a surrogate. ED 80..9F is the
/// legitimate U+D000..U+D7FF range; ED A0..BF is what a decoder that re-emits a
/// surrogate produces, and cli_heaps.cpp:87 produces it.
extern "C" void proof_utf16_never_emits_a_surrogate()
{
	std::uint8_t in[kUtf16Bytes];
	for (std::size_t i = 0; i < kUtf16Bytes; ++i) in[i] = nondet_u8();
	char out[kUtf8Cap];
	for (std::size_t i = 0; i < kUtf8Cap; ++i) out[i] = '\0';

	const std::size_t w = utf16leToUtf8(in, kUtf16Bytes, out, kUtf8Cap);

	for (std::size_t i = 0; i + 1 < w; ++i)
		assert(!(byteAt(out, i) == 0xED && byteAt(out, i + 1) >= 0xA0));
}

// ─── the two .NET entry points ───────────────────────────────────────────────

namespace {

/// src/cli_parser/cli_heaps.cpp:83, UserStringsHeap::utf16leToUtf8, transcribed.
/// Takes a unit count and no buffer size at all.
std::size_t dotnetHeaps(const std::uint8_t* src, std::size_t chars, char* out)
{
	std::size_t w = 0;
	for (std::size_t i = 0; i < chars; ++i)
	{
		const std::uint32_t cp = static_cast<std::uint32_t>(src[i * 2])
			| (static_cast<std::uint32_t>(src[i * 2 + 1]) << 8);
		if (cp < 0x80) out[w++] = static_cast<char>(cp);
		else if (cp < 0x800)
		{
			out[w++] = static_cast<char>(0xC0u | (cp >> 6));
			out[w++] = static_cast<char>(0x80u | (cp & 0x3Fu));
		}
		else
		{
			out[w++] = static_cast<char>(0xE0u | (cp >> 12));
			out[w++] = static_cast<char>(0x80u | ((cp >> 6) & 0x3Fu));
			out[w++] = static_cast<char>(0x80u | (cp & 0x3Fu));
		}
	}
	return w;
}

/// src/cli_parser/cli_reader.cpp:776, CLIReader::fieldConstantString,
/// transcribed. Same decoder, a byte count and an `i + 1 < size` convention.
std::size_t dotnetReader(const std::uint8_t* blob, std::size_t size, char* out)
{
	std::size_t w = 0;
	for (std::size_t i = 0; i + 1 < size; i += 2)
	{
		const std::uint32_t cu = static_cast<std::uint32_t>(blob[i])
			| (static_cast<std::uint32_t>(blob[i + 1]) << 8);
		if (cu < 0x80) out[w++] = static_cast<char>(cu);
		else if (cu < 0x800)
		{
			out[w++] = static_cast<char>(0xC0u | (cu >> 6));
			out[w++] = static_cast<char>(0x80u | (cu & 0x3Fu));
		}
		else
		{
			out[w++] = static_cast<char>(0xE0u | (cu >> 12));
			out[w++] = static_cast<char>(0x80u | ((cu >> 6) & 0x3Fu));
			out[w++] = static_cast<char>(0x80u | (cu & 0x3Fu));
		}
	}
	return w;
}

} // namespace

/// Spec property 7. The two duplicated .NET decoders agree byte for byte on the
/// prefix both accept -- the copy has not drifted yet. What the proof also
/// shows is that they agree in being wrong: proof_utf16_never_emits_a_surrogate
/// fails for either of them, because both encode a surrogate directly.
extern "C" void proof_the_two_dotnet_entry_points_agree()
{
	std::uint8_t in[kUtf16Bytes];
	for (std::size_t i = 0; i < kUtf16Bytes; ++i) in[i] = nondet_u8();
	char a[kUtf8Cap];
	char b[kUtf8Cap];

	const std::size_t wa = dotnetHeaps(in, kUnits, a);
	const std::size_t wb = dotnetReader(in, kUtf16Bytes, b);

	assert(wa == wb);
	for (std::size_t i = 0; i < kUtf8Cap; ++i)
		if (i < wa) assert(a[i] == b[i]);
}

/// And the kernel is a drop-in for both, everywhere their output was
/// well-formed: identical bytes whenever the input contains no surrogate. The
/// difference is confined to exactly the inputs on which they were wrong.
extern "C" void proof_the_kernel_matches_dotnet_off_the_surrogates()
{
	std::uint8_t in[kUtf16Bytes];
	for (std::size_t i = 0; i < kUtf16Bytes; ++i) in[i] = nondet_u8();
	for (std::size_t i = 0; i < kUnits; ++i)
	{
		const std::uint32_t u = static_cast<std::uint32_t>(in[i * 2])
			| (static_cast<std::uint32_t>(in[i * 2 + 1]) << 8);
		__ESBMC_assume(!(u >= kHighSurrogateFirst && u <= kLowSurrogateLast));
	}

	char a[kUtf8Cap];
	char b[kUtf8Cap];
	const std::size_t wa = dotnetHeaps(in, kUnits, a);
	const std::size_t wb = utf16leToUtf8(in, kUtf16Bytes, b, kUtf8Cap);

	assert(wa == wb);
	for (std::size_t i = 0; i < kUtf8Cap; ++i)
		if (i < wa) assert(a[i] == b[i]);
}

// ─── mutf8ToUtf8 ─────────────────────────────────────────────────────────────

/// Spec property 8. Six input bytes and three declared units: enough for one
/// supplementary character (two three-byte sequences, two units) with a byte to
/// spare, so the six-byte lookahead is exercised against the end of the buffer.
extern "C" void proof_mutf8_stays_inside_both_buffers()
{
	constexpr std::size_t kIn = 6;
	constexpr std::size_t kU = 3;
	std::uint8_t in[kIn];
	for (std::size_t i = 0; i < kIn; ++i) in[i] = nondet_u8();
	char out[kU * 4];

	const std::size_t inBytes = nondet_size();
	__ESBMC_assume(inBytes <= kIn);

	const Mutf8Result r = mutf8ToUtf8Ex(in, inBytes, kU, out, kU * 4);

	// The cursor never leaves the declared input, which is what makes the
	// six-byte surrogate-pair lookahead safe at the end of a heap.
	assert(r.consumed <= inBytes);
	// Output is bounded by the declared unit count, not by the byte count --
	// four per unit, the bound utf16_size justifies.
	assert(r.written <= utf8CapacityForMutf8(kU));
	assert(r.written <= kU * 4);
}

/// Termination for the worst input there is: every byte a lead in F8..FF, which
/// MUTF-8 has no sequence for. The cursor advances one byte per iteration, so
/// the loop finishes -- and it finishes AT the declared end, having consumed
/// everything, rather than stalling partway.
extern "C" void proof_mutf8_terminates_on_leads_that_encode_nothing()
{
	constexpr std::size_t kIn = 4;
	std::uint8_t in[kIn];
	for (std::size_t i = 0; i < kIn; ++i)
	{
		in[i] = nondet_u8();
		__ESBMC_assume(in[i] >= 0xF8);
	}
	char out[kIn * 4];

	const Mutf8Result r = mutf8ToUtf8Ex(in, kIn, kIn, out, kIn * 4);

	assert(r.consumed == kIn);          // exactly at the declared end
	assert(r.written == kIn * 3);       // one U+FFFD per byte
}

/// The cursor is exactly at the declared end whenever the byte count, not the
/// unit count, is what ran out -- so a caller that advances by `consumed` lands
/// where the next record begins.
extern "C" void proof_mutf8_cursor_lands_on_the_declared_end()
{
	constexpr std::size_t kIn = 4;
	std::uint8_t in[kIn];
	for (std::size_t i = 0; i < kIn; ++i) in[i] = nondet_u8();
	char out[kIn * 4];

	// Give it more units than there can be characters, so the byte count is
	// what stops it: every branch consumes at least one byte per unit.
	const Mutf8Result r = mutf8ToUtf8Ex(in, kIn, kIn, out, kIn * 4);
	assert(r.consumed == kIn);
}

/// The C0 80 fold is exact: it produces one 0x00 byte, not two, and not the
/// two-byte overlong form. This is what puts an embedded NUL in a JVM name and
/// is why jvm_class_parser.cpp:253 must split with bstr::terminatorAt.
extern "C" void proof_mutf8_nul_fold_is_exact()
{
	std::uint8_t in[4] = {0xC0, 0x80, 0, 0};
	in[2] = nondet_u8();
	__ESBMC_assume(in[2] < 0x80 && in[2] != 0);
	in[3] = nondet_u8();
	char out[8];

	const Mutf8Result r = mutf8ToUtf8Ex(in, 3, 2, out, 8);
	assert(r.written == 2);
	assert(r.consumed == 3);
	assert(out[0] == '\0');
	assert(out[1] == static_cast<char>(in[2]));
}

extern "C" void proof_mutf8_refuses_a_short_buffer()
{
	constexpr std::size_t kIn = 4;
	std::uint8_t in[kIn];
	for (std::size_t i = 0; i < kIn; ++i) in[i] = nondet_u8();
	char out[kIn * 4];
	for (std::size_t i = 0; i < kIn * 4; ++i) out[i] = '#';

	const std::size_t outCap = nondet_size();
	__ESBMC_assume(outCap < kIn * 4);

	const Mutf8Result r = mutf8ToUtf8Ex(in, kIn, kIn, out, outCap);
	assert(r.written == 0 && r.consumed == 0);
	for (std::size_t i = 0; i < kIn * 4; ++i) assert(out[i] == '#');
}

// ─── decimalRun ──────────────────────────────────────────────────────────────

/// Spec property 9: reads no byte at or beyond n, refuses an empty run, and
/// leaves value and end well defined either way.
extern "C" void proof_decimal_run_reads_within_bounds()
{
	constexpr std::size_t kLen = 6;
	char in[kLen];
	for (std::size_t i = 0; i < kLen; ++i) in[i] = nondet_char();

	const std::size_t n = nondet_size();
	__ESBMC_assume(n <= kLen);
	const std::size_t start = nondet_size();
	__ESBMC_assume(start <= kLen);

	std::uint64_t value = 12345;
	std::size_t end = SIZE_MAX;
	const bool ok = decimalRun(in, n, start, value, end);

	if (!ok)
	{
		assert(value == 0 && end == start);
		// False exactly when the run is empty or the value would not fit: with
		// six digits the second cannot happen, so an empty run is the reason.
		assert(start >= n || in[start] < '0' || in[start] > '9');
	}
	else
	{
		assert(end > start && end <= n);
		for (std::size_t i = start; i < kLen; ++i)
			if (i < end) assert(in[i] >= '0' && in[i] <= '9');
		// The run really did stop at a non-digit or at the end.
		assert(end == n || in[end] < '0' || in[end] > '9');
	}
}

/// The accumulation cannot wrap. Stated over the whole 64-bit domain by taking
/// one symbolic step of the recurrence rather than by running the loop, which
/// is the only way to reach values near UINT64_MAX at all.
extern "C" void proof_decimal_run_accumulates_without_wrapping()
{
	const std::uint64_t acc = nondet_u64();
	const std::uint64_t d = nondet_u64();
	__ESBMC_assume(d <= 9);

	const bool guard = !(acc > kMaxU64Div10 || (acc == kMaxU64Div10 && d > kMaxU64Mod10));

	// The guard admits a step exactly when the step is representable. Written
	// by division so the harness does not form the product it is checking.
	assert(guard == (acc <= (UINT64_MAX - d) / 10));
	if (guard)
	{
		const std::uint64_t next = acc * 10 + d;
		assert(next >= acc);
		assert((next - d) / 10 == acc);
	}
}

/// The digits it accepts are the value it reports, for a run short enough to
/// write out. The point is that no leading digit is dropped and none is
/// counted twice -- the failure mode a hand-rolled version has.
extern "C" void proof_decimal_run_value_is_the_digits()
{
	char in[3];
	for (std::size_t i = 0; i < 3; ++i)
	{
		in[i] = nondet_char();
		__ESBMC_assume(in[i] >= '0' && in[i] <= '9');
	}

	std::uint64_t value = 0;
	std::size_t end = 0;
	assert(decimalRun(in, 3, 0, value, end));
	assert(end == 3);
	assert(value == static_cast<std::uint64_t>(in[0] - '0') * 100
		+ static_cast<std::uint64_t>(in[1] - '0') * 10
		+ static_cast<std::uint64_t>(in[2] - '0'));
}
