/**
 * @file src/fsharp_emitter/fs_file_emitter.cpp
 */

#include "retdec/fsharp_emitter/fs_file_emitter.h"
#include "retdec/fsharp_emitter/fs_type_emitter.h"
#include "retdec/fsharp_emitter/fs_writer.h"

#include <algorithm>
#include <sstream>
#include <unordered_set>

namespace retdec {
namespace fsharp_emitter {

FsFileEmitter::FsFileEmitter(FsEmitOptions opts) : opts_(std::move(opts)) {}

// ─── fileHeader ──────────────────────────────────────────────────────────────

std::string FsFileEmitter::fileHeader(const BcModule& mod) const {
    std::ostringstream ss;
    ss << "// Auto-generated by RetDec F# emitter\n";
    if (!mod.name().empty()) ss << "// Assembly: " << mod.name() << "\n";
    if (!mod.targetFramework.empty()) ss << "// Framework: " << mod.targetFramework << "\n";
    ss << "\n";
    return ss.str();
}

// ─── collectOpenDecls ────────────────────────────────────────────────────────

std::vector<std::string> FsFileEmitter::collectOpenDecls(const BcModule& mod) const {
    std::unordered_set<std::string> seen;
    std::vector<std::string> opens;

    auto addOpen = [&](const std::string& ns) {
        if (!ns.empty() && seen.insert(ns).second)
            opens.push_back(ns);
    };

    // Always include common F# namespaces for CLR decompilation
    addOpen("System");
    addOpen("System.Collections.Generic");

    // From external refs
    for (const auto& [fqName, _] : mod.externalRefs()) {
        size_t dot = fqName.rfind('.');
        if (dot != std::string::npos)
            addOpen(fqName.substr(0, dot));
    }

    // From class namespaces
    for (const auto& cls : mod.classes()) {
        if (!cls.packageName.empty())
            addOpen(cls.packageName);
    }

    if (opts_.sortOpenDecls) {
        std::sort(opens.begin() + 2, opens.end()); // keep System first
    }
    return opens;
}

// ─── topLevelDecl ────────────────────────────────────────────────────────────

std::string FsFileEmitter::topLevelDecl(const BcModule& mod) const {
    // Determine the namespace/module from the first class's package
    std::string ns;
    for (const auto& cls : mod.classes()) {
        if (!cls.packageName.empty()) { ns = cls.packageName; break; }
    }
    if (ns.empty()) ns = mod.name().empty() ? "Decompiled" : mod.name();

    if (opts_.useNamespace)
        return "namespace " + ns;
    else
        return "module " + ns;
}

// ─── emit ────────────────────────────────────────────────────────────────────

FsEmitResult FsFileEmitter::emit(const BcModule& module) const {
    FsEmitResult result;

    FsWriter writer;
    FsTypeEmitter typeEmitter(writer);

    std::ostringstream out;

    if (opts_.emitFileHeader)
        out << fileHeader(module);

    // Top-level module/namespace declaration
    out << topLevelDecl(module) << "\n\n";

    // Open declarations
    auto opens = collectOpenDecls(module);
    for (const auto& ns : opens)
        out << "open " << ns << "\n";
    if (!opens.empty()) out << "\n";

    // Emit all types
    const auto& classes = module.classes();
    for (size_t i = 0; i < classes.size(); ++i) {
        typeEmitter.emitClass(classes[i], module);
        if (i + 1 < classes.size()) {
            for (int b = 0; b < opts_.blanksBetweenTypes; ++b)
                writer.blank();
        }
    }

    out << writer.str();

    result.source = out.str();
    return result;
}

} // namespace fsharp_emitter
} // namespace retdec
