#!/usr/bin/env bash
# check_std_includes.sh - a standard algorithm used without including its header.
#
# std::sort compiles without <algorithm> whenever some other header happened to
# pull it in. Which headers do that is a property of the standard library
# implementation, not of the standard, so a file that builds on one toolchain
# fails on the next:
#
#   tests/cfg/cfg_test.cpp:368:7: error: no member named 'sort' in namespace 'std'
#   tests/dex_parser/dex_parser_test.cpp:2036:9: error: no matching function for call to 'find'
#
# Both of those built here under g++ and under a local clang++, and both failed
# on CI's clang++ the first time standalone-check ran on this branch. The tree
# had 67 files in that state.
#
# This check does not require the whole tree to be clean, because most of the
# rest is behind the LLVM build or is vendored (src/pelib is tracked against the
# upstream PeLib fork, and reformatting it to add one include costs more than it
# is worth). It carries the known set in a baseline and fails on anything new,
# so the count can only go down.
#
# Usage:
#   bash scripts/check_std_includes.sh            # fail on any file not in the baseline
#   bash scripts/check_std_includes.sh --update   # rewrite the baseline from the tree
#
# Baseline: scripts/std_includes_baseline.txt
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

exec python3 - "$@" <<'PY'
import os
import re
import sys

BASELINE = "scripts/std_includes_baseline.txt"
UPDATE = "--update" in sys.argv[1:]

# name -> the header that actually declares it
NEEDS = {}
for n in ("sort stable_sort find find_if find_if_not count count_if copy copy_if "
          "transform all_of any_of none_of for_each min_element max_element remove "
          "remove_if unique reverse fill lower_bound upper_bound binary_search "
          "set_intersection partial_sort nth_element rotate shuffle clamp equal "
          "search generate replace replace_if includes merge swap_ranges").split():
    NEEDS[n] = "algorithm"
for n in ("accumulate", "iota"):
    NEEDS[n] = "numeric"

USE = re.compile(r"\bstd::(" + "|".join(sorted(NEEDS)) + r")\b")
INC = re.compile(r"^#include\s*<([a-z_]+)>", re.M)


def strip_comments_and_literals(text):
    """Blank out comments and string/char literals, keeping line structure.

    A comment that names std::find_if is not a call to it, and neither is the
    string "std::find_if" in a name table. Scanning the raw text made this
    check fail on a file whose only mention of an algorithm was the comment
    explaining why a cache had lost the name of one. Newlines are preserved so
    that #include lines are still found at the start of a line.
    """
    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == "/" and i + 1 < n and text[i + 1] == "/":
            while i < n and text[i] != "\n":
                out.append(" ")
                i += 1
        elif c == "/" and i + 1 < n and text[i + 1] == "*":
            out.append("  ")
            i += 2
            while i < n and not (text[i] == "*" and i + 1 < n and text[i + 1] == "/"):
                out.append("\n" if text[i] == "\n" else " ")
                i += 1
            if i < n:
                out.append("  ")
                i += 2
        elif c in "\"'":
            quote = c
            out.append(" ")
            i += 1
            while i < n and text[i] != quote:
                if text[i] == "\\" and i + 1 < n:
                    out.append("  ")
                    i += 2
                    continue
                out.append("\n" if text[i] == "\n" else " ")
                i += 1
            if i < n:
                out.append(" ")
                i += 1
        else:
            out.append(c)
            i += 1
    return "".join(out)

# Directories that are not this project's to format.
SKIP_DIRS = {".git", "build", "deps", "node_modules", "__pycache__"}

found = {}
for dirpath, dirnames, filenames in os.walk("."):
    dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
    for name in filenames:
        if not name.endswith((".cpp", ".cc", ".cxx", ".h", ".hpp")):
            continue
        path = os.path.join(dirpath, name)[2:].replace(os.sep, "/")
        with open(path, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        code = strip_comments_and_literals(text)
        have = set(INC.findall(code))
        want = {NEEDS[m.group(1)] for m in USE.finditer(code)}
        missing = sorted(want - have)
        if missing:
            found[path] = missing

if UPDATE:
    with open(BASELINE, "w", encoding="utf-8") as fh:
        fh.write("# Files that use a std algorithm without including its header.\n")
        fh.write("# Generated by scripts/check_std_includes.sh --update.\n")
        fh.write("# This list may shrink. Adding to it needs a reason.\n")
        for path in sorted(found):
            fh.write(f"{path} {','.join(found[path])}\n")
    print(f"baseline rewritten: {len(found)} file(s)")
    sys.exit(0)

baseline = set()
try:
    with open(BASELINE, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#"):
                baseline.add(line.split()[0])
except OSError:
    print(f"{BASELINE} is missing; run scripts/check_std_includes.sh --update")
    sys.exit(1)

new = sorted(set(found) - baseline)
fixed = sorted(baseline - set(found))

for path in new:
    print(f"{path}: uses a std algorithm without including <{'>, <'.join(found[path])}>")

if fixed:
    print(f"note: {len(fixed)} file(s) in the baseline no longer need it; "
          f"run --update to drop them")

print(f"{len(found)} file(s) affected, {len(baseline)} in the baseline")
if new:
    print(f"FAIL: {len(new)} file(s) not in the baseline")
    sys.exit(1)
print("OK: no new file uses a std algorithm without including its header")
PY
