/**
 * @file src/vbnet_emitter/vb_file_emitter.cpp
 */

#include "retdec/vbnet_emitter/vb_file_emitter.h"
#include "retdec/vbnet_emitter/vb_type_emitter.h"
#include "retdec/vbnet_emitter/vb_writer.h"

#include <algorithm>
#include <sstream>
#include <unordered_set>

namespace retdec {
namespace vbnet_emitter {

VbFileEmitter::VbFileEmitter(VbEmitOptions opts) : opts_(std::move(opts)) {}

std::string VbFileEmitter::fileHeader(const BcModule& mod) const {
    std::ostringstream ss;
    ss << "' Auto-generated by RetDec VB.NET emitter\n";
    if (!mod.name().empty()) ss << "' Assembly: " << mod.name() << "\n";
    if (!mod.targetFramework.empty()) ss << "' Framework: " << mod.targetFramework << "\n";
    ss << "\n";
    return ss.str();
}

std::vector<std::string> VbFileEmitter::collectImports(const BcModule& mod) const {
    std::unordered_set<std::string> seen;
    std::vector<std::string> imports;

    auto addImp = [&](const std::string& ns) {
        if (!ns.empty() && seen.insert(ns).second)
            imports.push_back(ns);
    };

    addImp("System");
    addImp("System.Collections.Generic");

    for (const auto& [fqName, _] : mod.externalRefs()) {
        size_t dot = fqName.rfind('.');
        if (dot != std::string::npos)
            addImp(fqName.substr(0, dot));
    }
    for (const auto& cls : mod.classes()) {
        if (!cls.packageName.empty())
            addImp(cls.packageName);
    }

    if (opts_.sortImports)
        std::sort(imports.begin() + 2, imports.end());
    return imports;
}

std::string VbFileEmitter::namespaceName(const BcModule& mod) const {
    for (const auto& cls : mod.classes()) {
        if (!cls.packageName.empty()) return cls.packageName;
    }
    return mod.name().empty() ? "Decompiled" : mod.name();
}

VbEmitResult VbFileEmitter::emit(const BcModule& module) const {
    VbEmitResult result;

    VbWriter writer;
    VbTypeEmitter typeEmitter(writer);

    std::ostringstream out;

    if (opts_.emitFileHeader)
        out << fileHeader(module);

    // Imports
    auto imports = collectImports(module);
    for (const auto& ns : imports)
        out << "Imports " << ns << "\n";
    if (!imports.empty()) out << "\n";

    // Namespace wrapper
    std::string ns = namespaceName(module);
    out << "Namespace " << ns << "\n\n";

    // Emit types
    writer.indent();
    const auto& classes = module.classes();
    for (size_t i = 0; i < classes.size(); ++i) {
        typeEmitter.emitClass(classes[i], module);
        if (i + 1 < classes.size()) {
            for (int b = 0; b < opts_.blanksBetweenTypes; ++b)
                writer.blank();
        }
    }
    writer.dedent();

    out << writer.str();
    out << "\nEnd Namespace\n";

    result.source = out.str();
    return result;
}

} // namespace vbnet_emitter
} // namespace retdec
