;; Generated by RetDec WebAssembly disassembler
(module
  (type (;0;) (func (param i32) (param i32) (result i32)))
  (func $add (export "add") (type 0)
    (param 0 i32)
    (param 1 i32)
    local.get 0
    local.get 1
    i32.add)
  (func $sub (export "sub") (type 0)
    (param 0 i32)
    (param 1 i32)
    local.get 0
    local.get 1
    i32.sub)
  (func $mul (export "mul") (type 0)
    (param 0 i32)
    (param 1 i32)
    local.get 0
    local.get 1
    i32.mul)
  (func $abs_diff (export "abs_diff") (type 0)
    (param 0 i32)
    (param 1 i32)
    (local 2 i32)
    local.get 0
    local.get 1
    i32.sub
    local.tee 2
    i32.const 0
    i32.lt_s
    if
    i32.const 0
    local.get 2
    i32.sub
    local.set 2
    end
    local.get 2)
)
