;; Generated by RetDec WebAssembly disassembler
(module
  (type (;0;) (func (param i32)))
  (type (;1;) (func (param i32) (param i32) (result i32)))
  (func $divide (export "divide") (type 1)
    (param 0 i32)
    (param 1 i32)
    local.get 1
    i32.eqz
    if
    i32.const 0
    ;; unknown_op 0x8
    unreachable
    end
    local.get 0
    local.get 1
    i32.div_s)
  (func $safe_index (export "safe_index") (type 1)
    (param 0 i32)
    (param 1 i32)
    local.get 0
    i32.const 0
    i32.lt_s
    if
    local.get 0
    ;; unknown_op 0x8
    nop
    end
    local.get 0
    local.get 1
    i32.ge_s
    if
    local.get 0
    ;; unknown_op 0x8
    nop
    end
    local.get 0)
  (func $safe_divide (export "safe_divide") (type 1)
    (param 0 i32)
    (param 1 i32)
    ;; unknown_op 0x6
    i64.div_s
    local.get 0
    local.get 1
    call $divide
    ;; unknown_op 0x7
    unreachable
    drop
    i32.const -1)
)
