;; Generated by RetDec WebAssembly disassembler
(module
  (type (;0;) (func (param i32) (param i32)))
  (type (;1;) (func (param i32) (param i32) (result i32)))
  (type (;2;) (func (result i32)))
  (func $store_array (export "store_array") (type 0)
    (param 0 i32)
    (param 1 i32)
    (local 2 i32)
    (local 3 i32)
    i32.const 0
    local.set 2
    loop
    local.get 2
    local.get 1
    i32.lt_s
    if
    local.get 0
    local.get 2
    i32.const 4
    i32.mul
    i32.add
    local.tee 3
    local.get 2
    i32.store align=4
    local.get 2
    i32.const 1
    i32.add
    local.set 2
    br 1
    end
    end)
  (func $sum_array (export "sum_array") (type 1)
    (param 0 i32)
    (param 1 i32)
    (local 2 i32)
    (local 3 i32)
    i32.const 0
    local.set 2
    i32.const 0
    local.set 3
    loop
    local.get 2
    local.get 1
    i32.lt_s
    if
    local.get 3
    local.get 0
    local.get 2
    i32.const 4
    i32.mul
    i32.add
    i32.load align=4
    i32.add
    local.set 3
    local.get 2
    i32.const 1
    i32.add
    local.set 2
    br 1
    end
    end
    local.get 3)
  (func $grow_and_check (export "grow_and_check") (type 2)
    i32.const 1
    memory.grow)
  (memory 0 (export "mem") 1)
)
