;; Generated by RetDec WebAssembly disassembler
(module
  (type (;0;) (func (param i32) (param i32) (result i32)))
  (type (;1;) (func (param i32) (param i32) (param i32) (result i32)))
  (func 0 (type 0)
    (param 0 i32)
    (param 1 i32)
    local.get 0
    local.get 1
    i32.add)
  (func 1 (type 0)
    (param 0 i32)
    (param 1 i32)
    local.get 0
    local.get 1
    i32.sub)
  (func 2 (type 0)
    (param 0 i32)
    (param 1 i32)
    local.get 0
    local.get 1
    i32.mul)
  (func 3 (type 0)
    (param 0 i32)
    (param 1 i32)
    local.get 0
    local.get 1
    local.get 0
    local.get 1
    i32.gt_s
    select)
  (func $dispatch (export "dispatch") (type 1)
    (param 0 i32)
    (param 1 i32)
    (param 2 i32)
    local.get 1
    local.get 2
    local.get 0
    call_indirect (type 0) 0)
  (func $apply_all (export "apply_all") (type 0)
    (param 0 i32)
    (param 1 i32)
    (local 2 i32)
    (local 3 i32)
    i32.const 0
    local.set 2
    i32.const 0
    local.set 3
    loop
    local.get 2
    i32.const 4
    i32.lt_s
    if
    local.get 3
    local.get 0
    local.get 1
    local.get 2
    call_indirect (type 0) 0
    i32.add
    local.set 3
    local.get 2
    i32.const 1
    i32.add
    local.set 2
    br 1
    end
    end
    local.get 3)
  (table 0 4 funcref)
  (elem (;0;) (table 0) (i32.const 0) funcref (ref.func 0) (ref.func 1) (ref.func 2) (ref.func 3))
)
