#ifndef RETDEC_GUI_PANELS_DECOMPILED_C_H
#define RETDEC_GUI_PANELS_DECOMPILED_C_H

#include "retdec/gui/panels/panel_base.h"

#include <QFont>
#include <QString>

QT_BEGIN_NAMESPACE
class QPlainTextEdit;
class QLabel;
class QToolBar;
class QStackedWidget;
QT_END_NAMESPACE

namespace retdec::gui::widgets {
class EmptyStateWidget;
}

namespace retdec::gui::panels {

/**
 * @brief DecompiledCPanel — read-only decompiled C output viewer.
 *
 * Shows the C source generated by the CodeGenPass with:
 *   - C syntax highlighting (keywords, types, strings, comments)
 *   - Line numbers in the gutter
 *   - Crypto / pattern annotations rendered as folded comment blocks
 *   - Copy-to-clipboard toolbar button
 *   - "Save as..." shortcut
 *
 * The panel is read-only to prevent the user from editing decompiled output
 * (annotations are applied via the FunctionListPanel rename workflow instead).
 */
class DecompiledCPanel : public PanelBase {
    Q_OBJECT
public:
    explicit DecompiledCPanel(QWidget* parent = nullptr);

    void setSource(const QString& cSource);
    /// Load from disk (uses chunked/async path for large files).
    bool setSourceFromPath(const QString& path);
    void clear() override;

    void applyEditorFont(const QFont& font);

    /** @brief Current editor text (for diff / export helpers). */
    QString documentText() const;

    /** Scroll to a function body in the full decompiled source (1-based lines). */
    void scrollToFunction(const QString& name, int startLine, int endLine = -1);

public slots:
    void onFunctionSelected(uint64_t address, const QString& name);
    void onSaveAs();

    /** Best-effort scroll to @p name or @p address in the loaded C source. */
    void scrollToFunction(uint64_t address, const QString& name);

private slots:
    void onCopyToClipboard();
    void onAsyncLoadTick();

private:
    void setupUI();
    void scheduleAsyncLoad(QString remainder);
    void updateEmptyState();

    QToolBar*      toolbar_   = nullptr;
    QLabel*        funcLabel_ = nullptr;
    QStackedWidget* bodyStack_ = nullptr;
    retdec::gui::widgets::EmptyStateWidget* emptyState_ = nullptr;
    QPlainTextEdit* view_     = nullptr;
    /// Full payload of an in-progress async load. We index into it via
    /// pendingLoadPos_ instead of mutating the string — mutating with
    /// QString::remove(0, n) on a multi-MB string is O(N) per call and
    /// turns the streamed load into an O(N²) worst case.
    QString        pendingLoad_;
    int            pendingLoadPos_   = 0;
    qint64         pendingLoadTotal_ = 0;
};

} // namespace retdec::gui::panels
#endif
