# cmake/modules/EmbedOpenCLKernels.cmake
#
# retdec_embed_opencl_kernels(TARGET targetName SOURCE_FILES file1.cl [file2.cl ...])
#
# For each .cl file, generates a .cpp file that exposes the kernel source
# as a const char* string and a size_t.
#
# The generated symbols follow the pattern:
#   namespace retdec::opencl::kernels {
#       extern const char* kKernelName;       // zero-terminated
#       extern const std::size_t kKernelNameSize;
#   }
#
# where KernelName is the filename stem with underscores for non-alphanumeric chars,
# first letter uppercased.  E.g. "parallel_disasm.cl" → kParallelDisasm / kParallelDisasmSize.
#
# Usage in CMakeLists.txt:
#   retdec_embed_opencl_kernels(
#       TARGET  retdec-opencl
#       SOURCES kernels/parallel_disasm.cl kernels/my_other_kernel.cl
#   )

cmake_minimum_required(VERSION 3.26)

function(retdec_embed_opencl_kernels)
    cmake_parse_arguments(ARG "" "TARGET" "SOURCES" ${ARGN})

    if(NOT ARG_TARGET)
        message(FATAL_ERROR "retdec_embed_opencl_kernels: TARGET is required")
    endif()
    if(NOT ARG_SOURCES)
        message(FATAL_ERROR "retdec_embed_opencl_kernels: SOURCES is required")
    endif()

    set(_generated_srcs)

    foreach(_cl_file IN LISTS ARG_SOURCES)
        # Resolve to absolute path relative to caller's source dir.
        if(NOT IS_ABSOLUTE "${_cl_file}")
            set(_cl_file "${CMAKE_CURRENT_SOURCE_DIR}/${_cl_file}")
        endif()

        get_filename_component(_stem "${_cl_file}" NAME_WE)  # e.g. parallel_disasm

        # Derive C++ identifier: capitalise first letter, rest as-is (underscores ok).
        string(SUBSTRING "${_stem}" 0 1 _first)
        string(SUBSTRING "${_stem}" 1  -1 _rest)
        string(TOUPPER "${_first}" _first_up)
        set(_ident "${_first_up}${_rest}")  # e.g. Parallel_disasm
        # Replace any remaining non-alphanumeric chars with underscore.
        string(REGEX REPLACE "[^a-zA-Z0-9_]" "_" _ident "${_ident}")

        set(_out_cpp "${CMAKE_CURRENT_BINARY_DIR}/embedded_${_stem}.cpp")

        # Use a CMake script to perform the embedding at build time.
        set(_embed_script "${CMAKE_CURRENT_BINARY_DIR}/embed_${_stem}.cmake")

        file(WRITE "${_embed_script}"
"cmake_minimum_required(VERSION 3.26)\n"
"file(READ \"${_cl_file}\" _content)\n"
"# Escape special characters for C string\n"
"string(REPLACE \"\\\\\" \"\\\\\\\\\" _content \"\${_content}\")\n"
"string(REPLACE \"\\\"\" \"\\\\\\\"\" _content \"\${_content}\")\n"
"string(REPLACE \"\\n\" \"\\\\n\"\n"
"       _content \"\${_content}\")\n"
"string(LENGTH \"\${_content}\" _len)\n"
"set(_out\n"
"\"// Auto-generated by EmbedOpenCLKernels.cmake — DO NOT EDIT\\n\"\n"
"\"#include <cstddef>\\n\\n\"\n"
"\"namespace retdec {\\n\"\n"
"\"namespace opencl {\\n\"\n"
"\"namespace kernels {\\n\\n\"\n"
"\"// NOLINTBEGIN\\n\"\n"
"\"const char* k${_ident} =\\n\"\n"
"\"    \\\"\\\${_content}\\\";\\n\"\n"
"\"const std::size_t k${_ident}Size = \\\${_len};\\n\"\n"
"\"// NOLINTEND\\n\\n\"\n"
"\"} // namespace kernels\\n\"\n"
"\"} // namespace opencl\\n\"\n"
"\"} // namespace retdec\\n\"\n"
")\n"
"file(WRITE \"${_out_cpp}\" \"\${_out}\")\n"
        )

        add_custom_command(
            OUTPUT  "${_out_cpp}"
            COMMAND "${CMAKE_COMMAND}" -P "${_embed_script}"
            DEPENDS "${_cl_file}" "${_embed_script}"
            COMMENT "Embedding OpenCL kernel: ${_stem}.cl"
            VERBATIM
        )

        list(APPEND _generated_srcs "${_out_cpp}")

        # Generate the companion header at configure time so that consumers
        # can #include it without waiting for build.
        set(_out_hdr "${CMAKE_CURRENT_BINARY_DIR}/embedded_${_stem}.h")
        file(WRITE "${_out_hdr}"
"// Auto-generated by EmbedOpenCLKernels.cmake — DO NOT EDIT\n"
"#pragma once\n"
"#include <cstddef>\n"
"namespace retdec {\n"
"namespace opencl {\n"
"namespace kernels {\n"
"extern const char* k${_ident};\n"
"extern const std::size_t k${_ident}Size;\n"
"} // namespace kernels\n"
"} // namespace opencl\n"
"} // namespace retdec\n"
        )

    endforeach()

    # Attach generated sources to the target.
    target_sources("${ARG_TARGET}" PRIVATE ${_generated_srcs})

    # Expose the generated directory as an include path.
    target_include_directories("${ARG_TARGET}"
        PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
endfunction()
