# MSVC + nvcc: CMake's CompilerIdCUDA.vcxproj uses MSBuild "CUDA X.Y.targets". CUDA 13.2's
# CUDA X.Y.Version.props sets CudaToolkitVersionedPath from $(CUDA_PATH_V13_2), not CUDA_PATH.
# Propagate the versioned env var (and CUDA_PATH) into try_compile subprocesses.
if(MSVC AND WIN32)
	set(_retdec_cuda_root "")
	if(CUDAToolkit_ROOT)
		set(_retdec_cuda_root "${CUDAToolkit_ROOT}")
	elseif(NOT DEFINED ENV{CUDA_PATH} OR "$ENV{CUDA_PATH}" STREQUAL "")
		set(_retdec_cuda_pf "$ENV{ProgramFiles}")
		if(NOT _retdec_cuda_pf)
			set(_retdec_cuda_pf "C:/Program Files")
		endif()
		file(GLOB _retdec_cuda_bases "${_retdec_cuda_pf}/NVIDIA GPU Computing Toolkit/CUDA/*")
		if(_retdec_cuda_bases)
			list(SORT _retdec_cuda_bases COMPARE NATURAL ORDER DESCENDING)
			foreach(_cand IN LISTS _retdec_cuda_bases)
				if(EXISTS "${_cand}/bin/nvcc.exe")
					set(_retdec_cuda_root "${_cand}")
					break()
				endif()
			endforeach()
		endif()
	else()
		set(_retdec_cuda_root "$ENV{CUDA_PATH}")
	endif()

	if(NOT _retdec_cuda_root STREQUAL "")
		set(ENV{CUDA_PATH} "${_retdec_cuda_root}")
		get_filename_component(_retdec_cuda_verdir "${_retdec_cuda_root}" NAME)
		if(_retdec_cuda_verdir MATCHES "^v([0-9]+)\\.([0-9]+)$")
			set(_retdec_cuda_env "CUDA_PATH_V${CMAKE_MATCH_1}_${CMAKE_MATCH_2}")
			set(ENV{${_retdec_cuda_env}} "${_retdec_cuda_root}")
			list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ${_retdec_cuda_env})
		endif()
		list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CUDA_PATH)
		if(_retdec_cuda_env)
			message(STATUS "MSVC+CUDA: try_compile env ${_retdec_cuda_env} + CUDA_PATH -> ${_retdec_cuda_root}")
		else()
			message(STATUS "MSVC+CUDA: try_compile env CUDA_PATH -> ${_retdec_cuda_root}")
		endif()
	endif()
	unset(_retdec_cuda_root)
endif()
