/**
 * @file src/eh_reconstruct/borland_eh.cpp
 * @brief Borland/Embarcadero C++ 32-bit exception handling reconstruction.
 *
 * ## Borland EH model (32-bit x86)
 *
 * Borland C++ Builder and Delphi/C++ Builder store C++ exception handling
 * using a Windows SEH-style linked list of exception frames on the stack,
 * but with proprietary frame structure and static handler tables.
 *
 * ### Function prolog pattern
 *
 * Every function that uses try/catch emits this prolog sequence:
 *
 *   PUSH <handler_addr>          ; 68 <imm32> — push the handler function VMA
 *   PUSH DWORD PTR FS:[0]        ; 64 FF 35 00 00 00 00 — push previous head
 *   MOV  DWORD PTR FS:[0], ESP   ; 64 89 25 00 00 00 00 — install this frame
 *
 * (Sometimes MOV replaces the last two with variations, but this 14-byte
 *  sequence is the canonical form generated by Borland C++ 5.x – XE.)
 *
 * The exception frame on the stack at the MOV instruction has this layout
 * (growing downward, so the first PUSH lands at the highest address):
 *
 *   ESP+8 : handler_addr       (from PUSH <handler_addr>)
 *   ESP+4 : prev_fs0           (from PUSH FS:[0])
 *   ESP+0 : saved_register     (optional; varies by compiler version)
 *
 * The Borland handler function (at handler_addr) is a shared dispatcher
 * (__ExceptInit or __BExcHandler).  The static handler data for the function
 * is passed as a second hidden argument or retrieved via a table indexed by
 * the function's exception handler frame pointer.
 *
 * ### Static handler table
 *
 * The handler function jumps into a per-function handler stub that references
 * a static TExceptRec table.  Each TExceptRec entry (16 bytes) describes one
 * try block:
 *
 *   struct TExceptRec {
 *     DWORD  tryStart;      // offset from function start to try body start
 *     DWORD  tryEnd;        // offset from function start to try body end
 *     DWORD  catchOffset;   // offset from function start to catch handler code
 *     DWORD  pTypeInfo;     // pointer to Borland TypeInfo (or 0 = catch-all)
 *   };
 *
 * A zero-filled entry (all fields == 0) terminates the table.
 *
 * ### Borland TypeInfo
 *
 * Borland's TypeInfo for C++ classes uses a layout that mirrors its Pascal
 * ancestry.  For exception catching, the relevant field is the class name,
 * stored as a Pascal ShortString (length-prefixed):
 *
 *   struct TTypeInfo {
 *     BYTE   kind;         // 7 = tkClass for C++ classes
 *     BYTE   nameLen;
 *     char   name[nameLen]; // class name, NOT NUL-terminated
 *     // ... more fields
 *   };
 *
 * ### Detection fallback
 *
 * If no prolog pattern is found (e.g., compiler optimised it away), we also
 * scan the .data section for arrays of TExceptRec-like structures that have
 * valid code VMAs in the tryStart/catchOffset fields, as a secondary heuristic.
 *
 * ### Callee-save register scanning
 *
 * Borland 32-bit typically saves EBX, ESI, EDI, EBP using PUSH instructions
 * in the prolog.  We detect these with a simple scan of the first 32 bytes of
 * each function for PUSH reg (0x50+reg) opcodes.
 */

#include <memory>
#include "retdec/eh_reconstruct/eh_reconstruct.h"
#include <algorithm>
#include <cstring>
#include <string>
#include <vector>

namespace retdec {
namespace eh_reconstruct {

// ─── Borland prolog pattern bytes ────────────────────────────────────────────
//
// PUSH imm32       : 0x68, <4 bytes>            (5 bytes)
// PUSH FS:[0]      : 0x64 0xFF 0x35 0x00 0x00 0x00 0x00   (7 bytes)
// MOV FS:[0], ESP  : 0x64 0x89 0x25 0x00 0x00 0x00 0x00   (7 bytes)
//
// Total: 19 bytes.  We match bytes at specific offsets.

static bool matchBorlandProlog(const IBinaryView& view, uint64_t vma,
                                uint32_t& handlerRVA) {
    // Byte 0: 0x68 (PUSH imm32)
    if (view.readU8(vma) != 0x68) return false;
    // Bytes 1..4: the immediate (handler address — we'll read as RVA later)
    // Byte 5: 0x64 (FS segment prefix)
    if (view.readU8(vma + 5) != 0x64) return false;
    // Bytes 6..7: 0xFF 0x35 (PUSH DWORD PTR [disp32])
    if (view.readU8(vma + 6) != 0xFF) return false;
    if (view.readU8(vma + 7) != 0x35) return false;
    // Bytes 8..11: 0x00000000 (FS:[0])
    if (view.readU32LE(vma + 8) != 0) return false;
    // Byte 12: 0x64 (FS segment prefix)
    if (view.readU8(vma + 12) != 0x64) return false;
    // Bytes 13..14: 0x89 0x25 (MOV DWORD PTR [disp32], ESP)
    if (view.readU8(vma + 13) != 0x89) return false;
    if (view.readU8(vma + 14) != 0x25) return false;
    // Bytes 15..18: 0x00000000 (FS:[0])
    if (view.readU32LE(vma + 15) != 0) return false;

    handlerRVA = view.readU32LE(vma + 1);
    return true;
}

// ─── Borland TypeInfo name ────────────────────────────────────────────────────

static std::string readBorlandTypeName(const IBinaryView& view, uint32_t typePtr) {
    if (typePtr == 0) return "...";  // catch-all

    uint64_t vma = typePtr;
    if (!view.isMapped(vma)) return "...";

    // Skip `kind` byte
    // uint8_t kind = view.readU8(vma);
    uint8_t nameLen = view.readU8(vma + 1);
    if (nameLen == 0 || nameLen > 128) return "unknown_type";

    char buf[129] = {};
    view.readBytes(vma + 2, reinterpret_cast<uint8_t*>(buf), nameLen);
    return std::string(buf, nameLen);
}

// ─── Parse Borland TExceptRec table ──────────────────────────────────────────

static void parseBorlandHandlerTable(const IBinaryView& view,
                                      uint64_t tableVma,
                                      uint64_t fnStart,
                                      EHFunction& fn) {
    // Each entry is 16 bytes.  Stop at all-zero entry or after 256 entries.
    for (int i = 0; i < 256; ++i) {
        uint64_t entryVma = tableVma + (uint64_t)i * 16;
        if (!view.isMapped(entryVma + 15)) break;

        uint32_t tryStart    = view.readU32LE(entryVma +  0);
        uint32_t tryEnd      = view.readU32LE(entryVma +  4);
        uint32_t catchOffset = view.readU32LE(entryVma +  8);
        uint32_t pTypeInfo   = view.readU32LE(entryVma + 12);

        // Terminator
        if (tryStart == 0 && tryEnd == 0 && catchOffset == 0 && pTypeInfo == 0)
            break;

        // Sanity: offsets should be plausible (< 1 MB function body is generous)
        if (tryEnd <= tryStart || tryEnd > 0x100000) continue;
        if (catchOffset > 0x100000) continue;

        TryCatchBlock block;
        block.tryBegin = fnStart + tryStart;
        block.tryEnd   = fnStart + tryEnd;

        CatchHandler ch;
        ch.handlerVma = fnStart + catchOffset;
        ch.isCatchAll = (pTypeInfo == 0);
        ch.catchType  = readBorlandTypeName(view, pTypeInfo);

        block.handlers.push_back(std::move(ch));
        fn.tryCatchBlocks.push_back(std::move(block));
        fn.hasEH = true;
    }
}

// ─── Parse callee-save registers from prolog ─────────────────────────────────

static void parseBorlandRegSaves(const IBinaryView& view,
                                  uint64_t fnStart,
                                  UnwindInfo& info) {
    // Borland typically starts with: PUSH EBP; MOV EBP,ESP; PUSH EBX; PUSH ESI; PUSH EDI
    // Scan first 32 bytes for PUSH reg opcodes (0x50 + reg)
    static const struct { uint8_t opcode; uint32_t regId; const char* name; } pushOps[] = {
        { 0x53, 3,  "ebx" },
        { 0x55, 5,  "ebp" },
        { 0x56, 6,  "esi" },
        { 0x57, 7,  "edi" },
    };

    int32_t stackDepth = 4;  // return address
    for (int byteOff = 0; byteOff < 32; ++byteOff) {
        uint8_t b = view.readU8(fnStart + byteOff);
        for (auto& op : pushOps) {
            if (b == op.opcode) {
                RegSave rs;
                rs.regId      = op.regId;
                rs.regName    = op.name;
                rs.frameOffset= -(int32_t)stackDepth;
                rs.isXmm      = false;
                info.regSaves.push_back(rs);
                stackDepth += 4;
                break;
            }
        }
        // Stop on call or jump
        if (b == 0xE8 || b == 0xFF || b == 0xE9 || b == 0xEB) break;
    }
}

// ─── Borland EH parser ────────────────────────────────────────────────────────

class BorlandEHParser final : public IEHParser {
public:
    const char* name() const noexcept override { return "Borland-EH"; }

    std::vector<EHFunction> parse(const IBinaryView& view) const override {
        std::vector<EHFunction> results;

        // Scan the .text section for Borland exception prolog patterns
        uint64_t textVma  = view.sectionVma(".text");
        std::size_t textSz = view.sectionSize(".text");
        if (textVma == 0 || textSz < 20) return results;

        uint64_t base = view.imageBase();

        // We need to identify function starts.  Without a symbol table here,
        // we scan every byte looking for the canonical prolog pattern.
        // Functions identified this way are guaranteed to have EH.

        std::vector<std::pair<uint64_t,uint32_t>> hits; // (fnVma, handlerAddr)

        for (std::size_t off = 0; off + 19 <= textSz; ++off) {
            uint64_t vma = textVma + off;
            uint32_t handlerAddr = 0;
            if (matchBorlandProlog(view, vma, handlerAddr)) {
                // Deduplicate: if a hit is within 4 bytes of a previous, skip
                bool dup = false;
                for (auto& h : hits)
                    if (vma - h.first < 8) { dup = true; break; }
                if (!dup) hits.push_back({vma, handlerAddr});
                off += 18;  // skip the rest of the prolog
            }
        }

        for (auto& [prologVma, handlerAddr] : hits) {
            // The function start is the prolog VMA (or slightly before if
            // PUSH EBP precedes; scan back up to 4 bytes)
            uint64_t fnStart = prologVma;
            for (int back = 1; back <= 4; ++back) {
                if (view.readU8(prologVma - back) == 0x55) {  // PUSH EBP
                    fnStart = prologVma - back;
                    break;
                }
            }

            EHFunction fn;
            fn.functionVma = fnStart;
            fn.functionEnd = fnStart + 0x1000;  // unknown; caller may tighten
            fn.unwindInfo.functionBegin = fnStart;
            fn.unwindInfo.functionEnd   = fn.functionEnd;

            parseBorlandRegSaves(view, fnStart, fn.unwindInfo);

            // The handler address from the prolog is an absolute VA.
            // From that address we need to find the TExceptRec table.
            // The Borland dispatcher stub starts with: MOV EAX, <tablePtr>; JMP __BExcHandler
            // or: PUSH <tablePtr>; ...
            // We look for a MOV EAX, imm32 (0xB8) within 16 bytes of handlerAddr.
            uint64_t handlerVma = (uint64_t)handlerAddr;
            if (!view.isMapped(handlerVma)) {
                // handlerAddr might be an RVA
                handlerVma = base + handlerAddr;
            }

            uint64_t tableVma = 0;
            if (view.isMapped(handlerVma)) {
                for (int i = 0; i < 16; ++i) {
                    if (view.readU8(handlerVma + i) == 0xB8) {  // MOV EAX, imm32
                        tableVma = view.readU32LE(handlerVma + i + 1);
                        if (!view.isMapped(tableVma) && view.isMapped(base + tableVma))
                            tableVma = base + tableVma;
                        break;
                    }
                }
                // Fallback: look for PUSH imm32 followed by CALL
                if (tableVma == 0) {
                    for (int i = 0; i < 16; ++i) {
                        if (view.readU8(handlerVma + i) == 0x68 &&
                            view.readU8(handlerVma + i + 5) == 0xE8) {
                            tableVma = view.readU32LE(handlerVma + i + 1);
                            if (!view.isMapped(tableVma))
                                tableVma = base + tableVma;
                            break;
                        }
                    }
                }
            }

            if (tableVma != 0 && view.isMapped(tableVma)) {
                parseBorlandHandlerTable(view, tableVma, fnStart, fn);
            }

            results.push_back(std::move(fn));
        }

        return results;
    }
};

std::unique_ptr<IEHParser> makeBorlandEHParser() {
    return std::make_unique<BorlandEHParser>();
}

} // namespace eh_reconstruct
} // namespace retdec
